import type { Graha } from './types'

/**
 * 나바그라하 9종 — L0 결과 유형.
 *
 * 물랑크(Moolank) = 태어난 '일(日)'의 자릿수 합. 27일생 → 2+7 = 9.
 * 생년월일만으로 100% 확정되므로 천체 계산이 필요 없다.
 * 나크샤트라는 시간을 모르면 23%가 틀리므로 L0에서 확정 표기하지 않는다.
 */
export const GRAHAS: readonly Graha[] = [
  {
    key: 'Sun',
    sanskrit: 'Surya',
    ko: '수리야',
    moolank: 1,
    weekday: '일요일',
    dashaYears: 6,
    color: '루비 레드',
    colorHex: '#C8102E',
    gemstone: '루비',
    deityKo: '시바 — 그리고 수리야 본인',
    direction: '동쪽', 
    luckyNumber: 1,
    mantra: '옴 흐람 흐림 흐라움 사하 수리야야 나마하',
    remedy: '해 뜰 때 동쪽을 보고 물을 한 번 부으라고 합니다.',
    keyword: '중심',
    copy: '나서지 않아도 시선이 모이는 쪽이에요. 자리를 비우면 바로 티가 나고요. 본인은 그게 부담스럽다고 하면서도 결국 그 자리로 돌아가요.',
    strengths: ['방향을 정하면 사람들이 알아서 따라온다', '책임이 무거울수록 오히려 안정된다', '겉치레가 아니라 결과로 인정받는다'],
    shadows: ['인정 못 받는 자리에선 급격히 시든다', '굽히는 법을 배우는 데 오래 걸린다', '무시당한 기억을 오래 들고 있다'],
  },
  {
    key: 'Moon',
    sanskrit: 'Chandra',
    ko: '찬드라',
    moolank: 2,
    weekday: '월요일',
    dashaYears: 10,
    color: '진주 백',
    colorHex: '#EDE7DA',
    gemstone: '진주',
    deityKo: '파르바티 — 어머니 여신',
    direction: '북서쪽', 
    luckyNumber: 2,
    mantra: '옴 슈람 슈림 슈라움 사하 찬드라야 나마하',
    remedy: '보름밤에 흰 음식을 나누라고 합니다.',
    keyword: '촉',
    copy: '말이 나오기 전에 이미 분위기를 읽어요. 남의 감정이 자기 것처럼 들어오는데, 그만큼 하루가 남 기분에 끌려다니기도 해요.',
    strengths: ['사람 마음을 정확히 짚는다', '돌볼 대상이 있으면 강해진다', '오래된 일도 그대로 기억한다'],
    shadows: ['남의 기분에 하루가 통째로 끌려간다', '거절을 미루다 자기가 소진된다', '괜찮은 척하는 게 습관이다'],
  },
  {
    key: 'Jupiter',
    sanskrit: 'Guru',
    ko: '구루',
    moolank: 3,
    weekday: '목요일',
    dashaYears: 16,
    color: '샤프란 옐로',
    colorHex: '#E8B93B',
    gemstone: '옐로 사파이어',
    deityKo: '브라흐마 — 그리고 스승 닥쉬나무르티',
    direction: '북동쪽', 
    luckyNumber: 3,
    mantra: '옴 그람 그림 그라움 사하 구라베 나마하',
    remedy: '목요일에 노란 음식을 남에게 대접하라고 합니다.',
    keyword: '신뢰',
    copy: '사람들이 자꾸 물어보러 와요. 배우는 것보다 가르치는 재능이 먼저 드러나는 쪽이고, 평판이 그대로 재산이 돼요.',
    strengths: ['설명하면 상대가 진짜로 이해한다', '멀리 보는 판단이 대체로 맞는다', '평판이 기회를 물어온다'],
    shadows: ['말이 앞서고 실행이 늦다', '남 일에 개입하다 자기 일을 놓친다', '조언하는 자리를 즐긴다'],
  },
  {
    key: 'Rahu',
    sanskrit: 'Rahu',
    ko: '라후',
    moolank: 4,
    weekday: null,
    dashaYears: 18,
    color: '스모크 그레이',
    colorHex: '#6B6B72',
    gemstone: '헤소나이트',
    deityKo: '두르가 — 사자를 탄 여신',
    direction: '남서쪽', 
    luckyNumber: 4,
    mantra: '옴 브람 브림 브라움 사하 라하베 나마하',
    remedy: '토요일 해 질 녘에 검은 참깨를 흐르는 물에 흘려보내라고 합니다.',
    keyword: '반전',
    copy: '흐름이 한 번 크게 뒤집히는 인생이에요. 남들 가는 길로 가면 이상하게 안 풀리고, 아무도 안 가는 쪽에서 길이 열려요.',
    strengths: ['새로 생긴 판에서 먼저 자리를 잡는다', '남이 못 보는 틈을 본다', '한 번의 도약이 크다'],
    shadows: ['안정된 구간을 못 견딘다', '과하게 밀어붙여 다 된 판을 깬다', '조급함이 결정을 망친다'],
  },
  {
    key: 'Mercury',
    sanskrit: 'Budha',
    ko: '부다',
    moolank: 5,
    weekday: '수요일',
    dashaYears: 17,
    color: '에메랄드 그린',
    colorHex: '#2E9E6B',
    gemstone: '에메랄드',
    deityKo: '비슈누 — 유지의 신',
    direction: '북쪽', 
    luckyNumber: 5,
    mantra: '옴 브람 브림 브라움 사하 부다야 나마하',
    remedy: '수요일에 초록 잎채소를 나누라고 합니다.',
    keyword: '말솜씨',
    copy: '같은 얘기를 훨씬 재미있게 옮기는 쪽이에요. 말과 글이 곧 수입이 되고, 어려운 걸 쉽게 만드는 게 이 사람 특기예요.',
    strengths: ['복잡한 걸 한 줄로 정리한다', '협상 자리에서 유리하다', '배우는 속도가 빠르다'],
    shadows: ['깊이 파기 전에 다음으로 넘어간다', '가벼워 보인다는 오해를 산다', '말로 넘길 수 있으면 넘긴다'],
  },
  {
    key: 'Venus',
    sanskrit: 'Shukra',
    ko: '슈크라',
    moolank: 6,
    weekday: '금요일',
    dashaYears: 20,
    color: '오팔 화이트',
    colorHex: '#F2E3E7',
    gemstone: '다이아몬드',
    deityKo: '락슈미 — 풍요의 여신',
    direction: '남동쪽', 
    luckyNumber: 6,
    mantra: '옴 드람 드림 드라움 사하 슈크라야 나마하',
    remedy: '금요일에 흰 꽃이나 향을 올리라고 합니다.',
    keyword: '매력',
    copy: '본인은 아무것도 안 했다는데 주변이 먼저 다가와요. 아름다운 걸 알아보는 눈이 있고, 그 취향이 그대로 일이 되는 쪽이에요.',
    strengths: ['가만히 있어도 사람이 붙는다', '취향이 곧 경쟁력이 된다', '분위기를 부드럽게 만든다'],
    shadows: ['갈등을 피하다 문제를 키운다', '좋아하는 것에 돈이 샌다', '싫은 소리를 끝까지 못 한다'],
  },
  {
    key: 'Ketu',
    sanskrit: 'Ketu',
    ko: '케투',
    moolank: 7,
    weekday: null,
    dashaYears: 7,
    color: '다갈색',
    colorHex: '#7A5C42',
    gemstone: '캣츠아이',
    deityKo: '가네샤 — 장애를 치우는 신',
    direction: null, 
    luckyNumber: 7,
    mantra: '옴 스람 스림 스라움 사하 케타베 나마하',
    remedy: '길 잃은 이에게 길을 알려주는 것이 이 행성의 처방이라고 합니다.',
    keyword: '통찰',
    copy: '겉으로 드러나기까지 오래 걸려요. 안에서는 이미 다 정리해뒀는데 꺼내질 않거든요. 알아주는 사람이 늦게 나타나는 편이에요.',
    strengths: ['혼자 하는 일에서 깊이가 나온다', '본질을 남보다 빨리 알아본다', '집착을 놓는 게 빠르다'],
    shadows: ['설명을 생략해서 오해를 산다', '자기를 과소평가한다', '알아주길 바라면서 말은 안 한다'],
  },
  {
    key: 'Saturn',
    sanskrit: 'Shani',
    ko: '샤니',
    moolank: 8,
    weekday: '토요일',
    dashaYears: 19,
    color: '인디고 블랙',
    colorHex: '#2B2F45',
    gemstone: '블루 사파이어',
    deityKo: '하누만 — 그리고 야마',
    direction: '서쪽', 
    luckyNumber: 8,
    mantra: '옴 프람 프림 프라움 사하 샤나이슈차라야 나마하',
    remedy: '토요일에 일하는 사람에게 먹을 것을 건네라고 합니다.',
    keyword: '버티는 힘',
    copy: '다들 나간 뒤에 결과를 챙기는 쪽이에요. 초반이 느린 대신, 늦게 온 게 오래 가요. 남들이 포기한 지점이 이 사람 출발선이에요.',
    strengths: ['오래 걸리는 일을 끝까지 간다', '어려운 시기에 오히려 단단해진다', '신용이 계속 쌓인다'],
    shadows: ['자기한테만 지나치게 엄격하다', '즐거움을 계속 나중으로 미룬다', '힘들다는 말을 안 한다'],
  },
  {
    key: 'Mars',
    sanskrit: 'Mangala',
    ko: '망갈라',
    moolank: 9,
    weekday: '화요일',
    dashaYears: 7,
    color: '코럴 레드',
    colorHex: '#D4462F',
    gemstone: '레드 코럴',
    deityKo: '하누만 — 그리고 카르티케야',
    direction: '남쪽', 
    luckyNumber: 9,
    mantra: '옴 크람 크림 크라움 사하 바우마야 나마하',
    remedy: '화요일에 붉은 것을 하나만 몸에 지니라고 합니다.',
    keyword: '추진력',
    copy: '시작을 겁내지 않아요. 몸으로 부딪쳐서 배우는 쪽이고요. 대신 한 번 데면 그 사람을 오래 기억해요.',
    strengths: ['결정이 빠르다', '위기 상황에서 제일 먼저 움직인다', '해보고 나서 판단한다'],
    shadows: ['화가 먼저 나가고 후회가 뒤따른다', '기다리는 구간을 못 견딘다', '지고 나서 며칠을 앓는다'],
  },
] as const
