import type { Nakshatra } from './types'

/** 나크샤트라 10~18 (Magha ~ Jyeshtha) */
export const NAKSHATRAS_10_18: readonly Nakshatra[] = [
  {
    index: 9,
    key: 'magha',
    sanskrit: 'Magha',
    devanagari: 'मघा',
    ko: '마가',
    archetype: '빈 왕좌',
    tagline: '무시당한 순간을 몇 년 뒤에도 기억하는 사람',
    lord: 'Ketu',
    deity: 'Pitris',
    deityKo: '피트리 — 조상의 혼',
    symbol: 'Royal throne',
    symbolKo: '왕좌',
    gana: 'Rakshasa',
    yoni: 'Rat',
    yoniKo: '쥐',
    nadi: 'Antya',
    range: [120, 133.3333],
    rashi: ['사자자리'],
    luckyColor: '고동 금빛',
    luckyColorHex: '#9C6B2F',
    gemstone: '루비',
    luckyNumber: 7,
    direction: '남서쪽',
    ratings: { wealth: 4, career: 4, love: 2, bond: 4, helper: 4 },
    keyword: '계승',
    copy: '앞선 사람의 자리를 이어받는 흐름이에요. 권위가 몸에 배어 있어서, 나서지 않아도 어른 대접을 받아요. 대신 함부로 대해진 기억은 절대 안 지워져요.',
    ritual: '큰 결정 전에는 돌아가신 분의 이름을 한 번 떠올리라고 해요.',
    strengths: ['자리에 맞는 무게를 자연스럽게 갖춘다', '전통과 형식을 다룰 줄 안다', '자기 사람은 끝까지 챙긴다'],
    shadows: ['예우받지 못하면 그 자리에서 마음이 닫힌다', '지나간 일을 놓지 못하고 되새긴다', '체면 때문에 손해를 감수한다'],
    career: ['공공·행정', '가업 승계', '문화재·아카이브', '의전·행사'],
    love: {
      headline: '존중받아야 열리는 사람.',
      points: ['예우받는 느낌이 무엇보다 중요합니다.', '무심코 던진 한마디에 며칠을 앓아요.', '왜 상했는지는 끝까지 말하지 않습니다.'],
    },
    wealth: {
      headline: '이어받는 돈복.',
      points: ['물려받거나 넘겨받는 형태의 자산이 따라옵니다.', '새는 곳은 대부분 체면 지출이에요. 거기만 잡으면 됩니다.', '자리가 올라갈수록 돈도 같이 따라오는 구조입니다.'],
    },
    work: {
      headline: '이어받는 자리.',
      points: ['새로 만들기보다 있는 것을 맡아 키우는 쪽이 맞아요.', '공공·가업·문화재처럼 형식이 있는 분야가 어울립니다.', '권위가 몸에 배어 있어 자리가 자연스럽습니다.'],
    },
    bond: '예우하는 사람과 오래 갑니다. 함부로 대한 사람은 조용히 정리해요.',
    helper: '윗사람이 지목해서 끌어줍니다. 내가 나서지 않아도 알아보는 사람이 있어요.',
    publicSelf: '품위 있고 어른스러운 사람',
    trueSelf: '무시당한 순간을 몇 년째 기억하는 사람',
    peak: { from: 35, to: 43, signals: ['이어받는 자리 얘기가 나온다', '윗사람이 나를 지목한다', '형식과 의전을 맡게 된다'] },
    cautions: ['체면 지출이 계속 샌다', '지나간 일을 되새기다 지금을 놓친다', '예우 못 받으면 그 자리에서 닫힌다'],
    compatible: ['uttara-phalguni', 'uttara-ashadha', 'purva-phalguni'],
    caution: 'swati',
  },
  {
    index: 10,
    key: 'purva-phalguni',
    sanskrit: 'Purva Phalguni',
    devanagari: 'पूर्व फाल्गुनी',
    ko: '푸르바 팔구니',
    archetype: '볕 드는 침상',
    tagline: '노는 데 진심이라 사람이 모이는 사람',
    lord: 'Venus',
    deity: 'Bhaga',
    deityKo: '바가 — 향유와 몫의 신',
    symbol: 'Front legs of a bed',
    symbolKo: '침대의 앞다리',
    gana: 'Manushya',
    yoni: 'Rat',
    yoniKo: '쥐',
    nadi: 'Madhya',
    range: [133.3333, 146.6667],
    rashi: ['사자자리'],
    luckyColor: '연분홍',
    luckyColorHex: '#E8879C',
    gemstone: '다이아몬드',
    luckyNumber: 6,
    direction: '남동쪽',
    ratings: { wealth: 3, career: 3, love: 5, bond: 3, helper: 4 },
    keyword: '향유',
    copy: '쉴 줄 아는 게 이 사람의 능력이에요. 모임을 잡으면 사람이 모이고, 그 자리를 즐겁게 만드는 감각에서 실제로 돈이 나와요.',
    ritual: '금요일엔 좋아하는 걸 하나 사서 자기한테 주라고 해요.',
    strengths: ['자리를 즐겁게 만드는 감각이 있다', '연출하고 꾸미는 재능이 실전에서 통한다', '베푸는 게 자연스러워서 적이 적다'],
    shadows: ['힘든 일은 일단 미룬다', '즐거우면 계획이 뒤로 밀린다', '쓸 때 기분 따라 써버린다'],
    career: ['공연·엔터테인먼트', '패션·뷰티', '호스피탈리티', '이벤트'],
    love: {
      headline: '연애 자체를 즐기는 사람.',
      points: ['함께 있는 시간이 재미있어야 합니다.', '재미가 사라지면 마음도 같이 식어요.', '같이 만들 즐거움이 계속 필요합니다.'],
    },
    wealth: {
      headline: '즐기면서 버는 돈복.',
      points: ['사람을 모으는 감각에서 실제로 수입이 나옵니다.', '기분 따라 쓰면 남는 게 없어요.', '들어오자마자 떼어놓는 방식만 통합니다.'],
    },
    work: {
      headline: '사람을 모으는 자리.',
      points: ['모임과 자리를 만드는 감각이 그대로 일이 됩니다.', '기획·연출·호스피탈리티가 맞아요.', '힘든 일을 미루는 습관이 유일한 제동입니다.'],
    },
    bond: '넓고 즐겁게 사귀어요. 힘든 얘기를 안 해서 깊어지는 데 시간이 걸립니다.',
    helper: '즐겁게 지낸 사람이 뜻밖의 기회를 물어옵니다. 일로 만난 사이보다 잘 통해요.',
    publicSelf: '밝고 같이 있으면 즐거운 사람',
    trueSelf: '힘든 얘기를 웃으면서 넘기는 사람',
    peak: { from: 26, to: 34, signals: ['모임을 맡아달라는 얘기가 온다', '취향이 콘텐츠가 된다', '사람을 통해 일이 들어온다'] },
    cautions: ['기분 따라 쓰면 남는 게 없다', '힘든 일을 계속 미룬다', '재미가 사라지면 관계도 식는다'],
    compatible: ['magha', 'purva-ashadha', 'chitra'],
    caution: 'ardra',
  },
  {
    index: 11,
    key: 'uttara-phalguni',
    sanskrit: 'Uttara Phalguni',
    devanagari: 'उत्तर फाल्गुनी',
    ko: '우타라 팔구니',
    archetype: '언약의 침상',
    tagline: '한 번 한 약속 때문에 자기가 손해 보는 사람',
    lord: 'Sun',
    deity: 'Aryaman',
    deityKo: '아리아만 — 계약과 우정의 신',
    symbol: 'Back legs of a bed',
    symbolKo: '침대의 뒷다리',
    gana: 'Manushya',
    yoni: 'Cow',
    yoniKo: '소',
    nadi: 'Adi',
    range: [146.6667, 160],
    rashi: ['사자자리', '처녀자리'],
    luckyColor: '밝은 주황',
    luckyColorHex: '#E5852B',
    gemstone: '루비',
    luckyNumber: 1,
    direction: '동쪽',
    ratings: { wealth: 4, career: 4, love: 4, bond: 5, helper: 4 },
    keyword: '언약',
    copy: '말한 건 지켜요. 상황이 바뀌어서 손해가 나도요. 그래서 이 사람이랑 일해본 사람들은 다시 찾아와요.',
    ritual: '약속을 맺는 날엔 두 사람이 같은 음식을 나눠 먹으라고 해요.',
    strengths: ['한 번 신뢰를 주면 오래 간다', '동업이나 협업에서 특히 힘이 난다', '돕는 데 조건을 안 붙인다'],
    shadows: ['배신당하면 회복에 몇 년이 걸린다', '이미 어긋난 약속도 혼자 지키고 있다', '형식과 절차에 지나치게 매인다'],
    career: ['법무·계약', '컨설팅', '결혼·중개', '공공 서비스'],
    love: {
      headline: '결혼까지 생각하고 만나는 사람.',
      points: ['안정을 주는 대신 같은 무게를 요구합니다.', '가벼운 관계를 원하는 사람과는 어긋나요.', '한 번 맺으면 좀처럼 끊지 않습니다.'],
    },
    wealth: {
      headline: '같이 벌어야 커지는 돈복.',
      points: ['동업과 협업에서 수익 구간이 확 달라집니다.', '혼자 다 하려 하면 오히려 더디게 가요.', '신뢰가 자산이라 한 번 쌓이면 오래 갑니다.'],
    },
    work: {
      headline: '함께 하는 자리.',
      points: ['동업·계약·중개처럼 신뢰가 자산인 일이 맞습니다.', '혼자보다 둘일 때 결과가 훨씬 큽니다.', '형식과 절차를 다루는 데 강해요.'],
    },
    bond: '한 번 맺으면 오래 갑니다. 27종 중 인연이 가장 안 끊기는 축이에요.',
    helper: '오래 알던 사람이 결정적인 자리를 소개해줍니다. 새 인맥보다 옛 인맥이 강해요.',
    publicSelf: '약속을 지키는 반듯한 사람',
    trueSelf: '이미 어긋난 약속도 혼자 지키는 사람',
    peak: { from: 32, to: 40, signals: ['동업이나 계약 얘기가 나온다', '중재를 부탁받는다', '오래된 관계가 일이 된다'] },
    cautions: ['배신당하면 회복에 몇 년이 걸린다', '형식에 매여 융통성을 잃는다', '손해를 알면서 약속을 지킨다'],
    compatible: ['rohini', 'magha', 'ashwini'],
    caution: 'shatabhisha',
  },
  {
    index: 12,
    key: 'hasta',
    sanskrit: 'Hasta',
    devanagari: 'हस्त',
    ko: '하스타',
    archetype: '만드는 손',
    tagline: '설명하는 대신 그냥 만들어서 보여주는 사람',
    lord: 'Moon',
    deity: 'Savitar',
    deityKo: '사비타르 — 태양의 장인 신',
    symbol: 'Open hand',
    symbolKo: '펼친 손',
    gana: 'Deva',
    yoni: 'Buffalo',
    yoniKo: '물소',
    nadi: 'Adi',
    range: [160, 173.3333],
    rashi: ['처녀자리'],
    luckyColor: '밝은 초록',
    luckyColorHex: '#4CA96B',
    gemstone: '진주',
    luckyNumber: 2,
    direction: '북서쪽',
    ratings: { wealth: 4, career: 5, love: 3, bond: 3, helper: 3 },
    keyword: '솜씨',
    copy: '머릿속에 있는 걸 손으로 꺼내는 재능이 있어요. 잔손 많이 가는 일을 안 지겨워하고, 그 정교함이 결국 이 사람 값이 돼요.',
    ritual: '새벽에 손을 씻고 그날 만들 걸 한 줄 적으라고 해요.',
    strengths: ['디테일에서 실력 차이가 드러난다', '생각한 걸 바로 실물로 만든다', '농담으로 분위기를 푼다'],
    shadows: ['디테일에 매여 마감을 넘긴다', '남이 만든 결과물의 허술함을 못 참는다', '말로 표현할 걸 자꾸 물건으로 대신한다'],
    career: ['공예·제조', '디자인·개발', '의료 시술', '요리·제과'],
    love: {
      headline: '행동으로 표현하는 사람.',
      points: ['말 대신 만들어다 주고 챙겨줍니다.', '상대는 말로 듣고 싶어 하는 경우가 많아요.', '표현을 물건으로만 대신하고 있진 않은지 보세요.'],
    },
    wealth: {
      headline: '손끝에서 나오는 돈복.',
      points: ['기술과 정교함이 그대로 값이 됩니다.', '남 밑에서보다 이름을 걸 때 수익이 뜁니다.', '만든 결과물이 다음 일을 물어오는 구조예요.'],
    },
    work: {
      headline: '만드는 자리.',
      points: ['손끝의 정교함이 그대로 값이 됩니다.', '이름을 걸고 할 때 수익 구간이 확 달라져요.', '결과물이 다음 일을 물어오는 구조입니다.'],
    },
    bond: '말보다 행동으로 표현해서, 상대가 알아채기까지 시간이 걸려요.',
    helper: '내가 만든 결과물을 보고 사람이 찾아옵니다. 영업보다 작업이 먼저입니다.',
    publicSelf: '손재주 좋고 야무진 사람',
    trueSelf: '말로 할 걸 자꾸 만들어서 대신하는 사람',
    peak: { from: 29, to: 37, signals: ['내 이름을 걸 기회가 온다', '남이 못 만든 걸 맡게 된다', '디테일로 값이 매겨진다'] },
    cautions: ['디테일에 매여 마감을 넘긴다', '남의 허술함을 못 참아 혼자 다 한다', '표현을 물건으로만 한다'],
    compatible: ['chitra', 'mrigashira', 'krittika'],
    caution: 'purva-bhadrapada',
  },
  {
    index: 13,
    key: 'chitra',
    sanskrit: 'Chitra',
    devanagari: 'चित्रा',
    ko: '치트라',
    archetype: '장인의 보석',
    tagline: '나가기 전에 거울 앞에서 한 번 더 서는 사람',
    lord: 'Mars',
    deity: 'Tvashtar (Vishvakarma)',
    deityKo: '비슈바카르마 — 신들의 건축가',
    symbol: 'Shining jewel',
    symbolKo: '빛나는 보석',
    gana: 'Rakshasa',
    yoni: 'Tiger',
    yoniKo: '호랑이',
    nadi: 'Madhya',
    range: [173.3333, 186.6667],
    rashi: ['처녀자리', '천칭자리'],
    luckyColor: '보석 청록',
    luckyColorHex: '#1F8A8A',
    gemstone: '레드 코럴',
    luckyNumber: 9,
    direction: '남쪽',
    ratings: { wealth: 4, career: 4, love: 4, bond: 2, helper: 3 },
    keyword: '연출',
    copy: '같은 걸 줘도 이 사람이 손대면 더 좋아 보여요. 자기 자신도 하나의 작품처럼 다듬고요. 그 감각이 곧 직업이 되는 자리예요.',
    ritual: '중요한 자리 전엔 거울 앞에서 딱 한 곳만 고치라고 해요.',
    strengths: ['완성도를 남들보다 한 단계 위로 올린다', '구조를 설계하는 눈이 있다', '들어서면 공기가 바뀐다'],
    shadows: ['보이는 데 쓰는 돈이 계속 늘어난다', '비교당하는 상황을 못 견딘다', '준비가 덜 됐다며 자리를 피한다'],
    career: ['건축·인테리어', '브랜딩·아트디렉션', '주얼리·패션', '영상'],
    love: {
      headline: '보이는 게 중요한 사람.',
      points: ['상대가 편해져서 꾸미지 않으면 서운합니다.', '그 이유를 말하기가 좀 그래서 혼자 담아둬요.', '내면을 볼 시간을 스스로에게 줘야 합니다.'],
    },
    wealth: {
      headline: '감각으로 버는 돈복.',
      points: ['보여주는 완성도가 곧 단가입니다.', '쓰는 것도 감각을 따라가니 상한선이 필요해요.', '보이는 데 들어가는 돈이 계속 늘어나는 게 함정입니다.'],
    },
    work: {
      headline: '보여주는 자리.',
      points: ['완성도를 한 단계 위로 올리는 게 실력입니다.', '브랜딩·공간·영상처럼 감각이 값인 분야가 맞아요.', '포트폴리오가 곧 인맥이 됩니다.'],
    },
    bond: '끌리는 사람이 많은데 오래 남는 사람은 적어요. 편해진 관계를 지루해하는 게 원인입니다.',
    helper: '내 작업을 알아본 사람이 다음 판을 열어줍니다. 포트폴리오가 곧 인맥이에요.',
    publicSelf: '세련되고 눈에 띄는 사람',
    trueSelf: '비교당하는 게 제일 견디기 힘든 사람',
    peak: { from: 30, to: 38, signals: ['보여주는 자리를 맡게 된다', '감각으로 값이 매겨진다', '이름이 앞에 붙는 일이 온다'] },
    cautions: ['보이는 데 쓰는 돈이 계속 는다', '준비가 덜 됐다며 기회를 피한다', '편해진 상대에게 서운함을 쌓는다'],
    compatible: ['hasta', 'purva-phalguni', 'vishakha'],
    caution: 'bharani',
  },
  {
    index: 14,
    key: 'swati',
    sanskrit: 'Swati',
    devanagari: 'स्वाति',
    ko: '스와티',
    archetype: '바람의 새싹',
    tagline: '힘들어도 도와달라는 말이 안 나오는 사람',
    lord: 'Rahu',
    deity: 'Vayu',
    deityKo: '바유 — 바람의 신',
    symbol: 'Young sprout swaying in wind',
    symbolKo: '바람에 흔들리는 새싹',
    gana: 'Deva',
    yoni: 'Buffalo',
    yoniKo: '물소',
    nadi: 'Antya',
    range: [186.6667, 200],
    rashi: ['천칭자리'],
    luckyColor: '하늘색',
    luckyColorHex: '#6FB3D9',
    gemstone: '헤소나이트',
    luckyNumber: 4,
    direction: '남서쪽',
    ratings: { wealth: 3, career: 4, love: 3, bond: 2, helper: 2 },
    keyword: '독립',
    copy: '누구한테 기대는 걸 제일 싫어해요. 흔들리긴 하는데 꺾이진 않고, 결국 자기 힘으로 자리를 만들어요. 자유가 이 사람의 조건이에요.',
    ritual: '바람 부는 날 창을 열고 하고 싶은 일을 소리 내어 말하라고 해요.',
    strengths: ['혼자서도 결과를 낸다', '어느 쪽으로도 안 치우친다', '어디에 떨어뜨려놔도 살아남는다'],
    shadows: ['도와달라는 말이 끝까지 안 나온다', '얽매인다 싶으면 관계를 정리해버린다', '혼자 하다 필요 이상으로 오래 걸린다'],
    career: ['1인 사업·프리랜서', '무역·유통', '외교·중재', '항공·운송'],
    love: {
      headline: '구속받으면 식는 사람.',
      points: ['연락 자주 하자는 말을 통제로 받아들이기 쉽습니다.', '각자의 공간을 인정하는 상대와 맞아요.', '그 차이를 서로 맞추는 게 관건입니다.'],
    },
    wealth: {
      headline: '혼자 굴리는 돈복.',
      points: ['스스로 벌어서 스스로 관리하는 구조가 맞습니다.', '언제든 뺄 수 있는 형태를 좋아해 장기 자산이 늦어요.', '조직 안에서는 실력만큼 보상을 못 받는 편입니다.'],
    },
    work: {
      headline: '혼자 굴리는 자리.',
      points: ['1인 사업·프리랜서 구조가 가장 잘 맞습니다.', '조직 안에서는 실력만큼 평가를 못 받는 편이에요.', '어디에 떨어뜨려놔도 살아남습니다.'],
    },
    bond: '거리를 두는 만큼 오래 갑니다. 매일 붙어 있는 관계는 오히려 빨리 끝나요.',
    helper: '도와달라고 말만 하면 나설 사람이 있는데, 그 말을 안 해서 기회를 놓칩니다.',
    publicSelf: '자유롭고 어디서든 잘 지내는 사람',
    trueSelf: '도와달라는 말이 끝내 안 나오는 사람',
    peak: { from: 31, to: 39, signals: ['혼자 하는 일에서 성과가 난다', '중재를 부탁받는다', '이동이나 해외 얘기가 나온다'] },
    cautions: ['혼자 하다 필요 이상으로 오래 걸린다', '얽매인다 싶으면 관계를 정리한다', '유동성을 좋아해 장기 자산이 늦다'],
    compatible: ['shatabhisha', 'punarvasu', 'mrigashira'],
    caution: 'rohini',
  },
  {
    index: 15,
    key: 'vishakha',
    sanskrit: 'Vishakha',
    devanagari: 'विशाखा',
    ko: '비샤카',
    archetype: '개선의 문',
    tagline: '정한 건 끝을 봐야 잠이 오는 사람',
    lord: 'Jupiter',
    deity: 'Indra & Agni',
    deityKo: '인드라·아그니 — 승리와 불의 신',
    symbol: 'Triumphal arch',
    symbolKo: '개선문',
    gana: 'Rakshasa',
    yoni: 'Tiger',
    yoniKo: '호랑이',
    nadi: 'Antya',
    range: [200, 213.3333],
    rashi: ['천칭자리', '전갈자리'],
    luckyColor: '황금 주황',
    luckyColorHex: '#D98324',
    gemstone: '옐로 사파이어',
    luckyNumber: 3,
    direction: '북동쪽',
    ratings: { wealth: 4, career: 5, love: 3, bond: 2, helper: 3 },
    keyword: '집념',
    copy: '목표를 정하면 다른 게 안 보여요. 늦게 시작해도 결국 도착하는 쪽이고요. 문제는 도착할 때쯤 옆에 사람이 몇 명 줄어 있다는 거예요.',
    ritual: '목표를 정한 날엔 그 이유를 한 문장으로 적어 보이는 데 두라고 해요.',
    strengths: ['한번 잡은 목표를 놓지 않는다', '경쟁 상황에서 오히려 살아난다', '거절당해도 다시 두드린다'],
    shadows: ['목표에 몰두하다 사람을 놓친다', '성과가 늦어지면 주변에 날이 선다', '쉬는 걸 낭비로 여긴다'],
    career: ['영업·성과 조직', '스포츠·경쟁 분야', '창업', '연구 개발'],
    love: {
      headline: '쟁취하듯 다가가는 사람.',
      points: ['얻기까지의 집중력이 대단합니다.', '얻고 난 뒤에도 그때만큼 하는지가 시험대예요.', '목표를 같이 보는 상대와 오래 갑니다.'],
    },
    wealth: {
      headline: '몰아서 버는 돈복.',
      points: ['집중 투자로 크게 만드는 유형입니다.', '분산을 답답해하다 크게 잃는 구간이 옵니다.', '목표를 숫자로 두면 실제로 도달합니다.'],
    },
    work: {
      headline: '경쟁하는 자리.',
      points: ['성과가 숫자로 보이는 일에서 최고치가 나옵니다.', '늦게 시작해도 결국 앞서는 유형이에요.', '과정에서 사람을 놓치는 게 유일한 비용입니다.'],
    },
    bond: '목표를 같이 보는 사람과 오래 가요. 속도가 다르면 금방 멀어집니다.',
    helper: '나를 인정한 경쟁자가 나중에 동료가 됩니다. 적이 귀인이 되는 유형이에요.',
    publicSelf: '목표가 뚜렷하고 추진력 있는 사람',
    trueSelf: '쉬는 걸 낭비로 여기는 사람',
    peak: { from: 33, to: 42, signals: ['경쟁 자리에 놓인다', '늦게 시작한 일이 앞서기 시작한다', '성과를 숫자로 보여줄 기회가 온다'] },
    cautions: ['목표에 몰두하다 사람을 놓친다', '성과가 늦으면 주변에 날이 선다', '분산을 답답해하다 크게 잃는다'],
    compatible: ['uttara-ashadha', 'chitra', 'dhanishta'],
    caution: 'revati',
  },
  {
    index: 16,
    key: 'anuradha',
    sanskrit: 'Anuradha',
    devanagari: 'अनुराधा',
    ko: '아누라다',
    archetype: '벗의 연꽃',
    tagline: '낯선 데 떨어뜨려 놔도 결국 사람을 모으는 사람',
    lord: 'Saturn',
    deity: 'Mitra',
    deityKo: '미트라 — 우정과 협약의 신',
    symbol: 'Lotus flower',
    symbolKo: '연꽃',
    gana: 'Deva',
    yoni: 'Deer',
    yoniKo: '사슴',
    nadi: 'Madhya',
    range: [213.3333, 226.6667],
    rashi: ['전갈자리'],
    luckyColor: '깊은 보라',
    luckyColorHex: '#6B4A8A',
    gemstone: '블루 사파이어',
    luckyNumber: 8,
    direction: '서쪽',
    ratings: { wealth: 3, career: 4, love: 4, bond: 5, helper: 5 },
    keyword: '결속',
    copy: '아는 사람 하나 없는 데 가도 반년이면 사람들이 모여 있어요. 직급이 아니라 신뢰로 묶는 쪽이고, 같이 고생한 사람과는 평생 가요.',
    ritual: '초승달엔 고마운 사람 한 명한테 연락하라고 해요.',
    strengths: ['모은 사람이 잘 안 흩어진다', '어려운 시기를 같이 버텨준다', '낯선 환경일수록 강해진다'],
    shadows: ['관계에 지나치게 헌신해서 자기가 남지 않는다', '속마음을 한참 뒤에야 꺼낸다', '거절을 못 해서 일이 몰린다'],
    career: ['조직·팀 리딩', '해외 사업', '커뮤니티·비영리', '기획'],
    love: {
      headline: '천천히 깊어지는 사람.',
      points: ['마음은 진작 정했는데 표현이 늦습니다.', '상대가 아직 아무 사이 아니라고 생각하는 구간이 길어요.', '한 번 정하면 오래 갑니다.'],
    },
    wealth: {
      headline: '사람이 물어오는 돈복.',
      points: ['인맥에 쓴 돈이 실제로 회수되는 몇 안 되는 유형이에요.', '고생을 같이 한 사람에게서 기회가 옵니다.', '혼자 벌려 하면 규모가 안 커집니다.'],
    },
    work: {
      headline: '팀을 맡는 자리.',
      points: ['낯선 환경일수록 오히려 실력이 드러납니다.', '해외·신규 조직처럼 처음부터 짜는 일이 맞아요.', '모은 사람이 잘 흩어지지 않습니다.'],
    },
    bond: '한 번 모은 사람이 잘 안 흩어져요. 27종 중 인연복이 가장 두터운 축입니다.',
    helper: '같이 고생한 사람이 평생 갑니다. 편하게 만난 사이보다 훨씬 강해요.',
    publicSelf: '두루 잘 지내고 사람을 모으는 사람',
    trueSelf: '속마음을 한참 뒤에야 꺼내는 사람',
    peak: { from: 32, to: 40, signals: ['낯선 곳에서 자리를 잡는다', '팀을 맡아달라는 얘기가 온다', '고생을 같이 한 사람에게서 기회가 온다'] },
    cautions: ['관계에 헌신하다 자기가 남지 않는다', '거절을 못 해 일이 몰린다', '표현이 늦어 오해를 산다'],
    compatible: ['rohini', 'pushya', 'bharani'],
    caution: 'dhanishta',
  },
  {
    index: 17,
    key: 'jyeshtha',
    sanskrit: 'Jyeshtha',
    devanagari: 'ज्येष्ठा',
    ko: '지에쉬타',
    archetype: '맏이의 부적',
    tagline: '힘든 티 안 내고 앞에 서 버리는 사람',
    lord: 'Mercury',
    deity: 'Indra',
    deityKo: '인드라 — 신들의 왕',
    symbol: 'Circular amulet',
    symbolKo: '둥근 부적',
    gana: 'Rakshasa',
    yoni: 'Deer',
    yoniKo: '사슴',
    nadi: 'Adi',
    range: [226.6667, 240],
    rashi: ['전갈자리'],
    luckyColor: '진한 적갈',
    luckyColorHex: '#8A3324',
    gemstone: '에메랄드',
    luckyNumber: 5,
    direction: '북쪽',
    ratings: { wealth: 3, career: 5, love: 2, bond: 4, helper: 3 },
    keyword: '보호',
    copy: '실제 순서가 몇째든 맏이 역할을 하게 돼요. 책임이 먼저 오고 지켜야 할 사람이 생기는데, 그 무게를 티내는 법이 없어요.',
    ritual: '힘든 날엔 붉은 실을 손목에 감으라고 해요.',
    strengths: ['위험한 자리에 먼저 선다', '아랫사람을 끝까지 데리고 간다', '판단이 빠르고 정확하다'],
    shadows: ['혼자 감당하다 어느 순간 고립된다', '자존심 때문에 도움을 거절한다', '괜찮냐고 물으면 무조건 괜찮다고 한다'],
    career: ['조직 관리', '보안·감사', '위기 대응', '전문직'],
    love: {
      headline: '보호하는 방식으로 사랑하는 사람.',
      points: ['앞에 서서 막아주는 게 애정 표현입니다.', '상대를 지켜야 할 대상으로만 두면 동등해지지 않아요.', '기대는 법을 배우면 관계가 달라집니다.'],
    },
    wealth: {
      headline: '책임이 큰 만큼 지출도 큰 돈복.',
      points: ['벌이는 나쁘지 않은데 나가는 몫이 큽니다.', '자기 몫부터 확보하는 원칙이 없으면 계속 이 상태예요.', '맡은 자리가 커질수록 수입도 같이 올라갑니다.'],
    },
    work: {
      headline: '책임지는 자리.',
      points: ['위기 관리와 조직 운영처럼 앞에 서야 하는 일이 맞습니다.', '판단이 빠르고 정확해 급할수록 강해요.', '혼자 감당하다 고립되는 걸 조심해야 합니다.'],
    },
    bond: '지켜주는 방식으로 이어가요. 동등하게 기대는 관계는 오히려 어색해합니다.',
    helper: '내가 감싸준 사람이 나중에 나를 감쌉니다. 다만 그때까지 혼자 버텨야 해요.',
    publicSelf: '든든하고 앞에 서는 사람',
    trueSelf: '괜찮냐고 물으면 무조건 괜찮다고 하는 사람',
    peak: { from: 34, to: 42, signals: ['위기 상황을 맡게 된다', '아랫사람이 늘어난다', '책임지는 자리로 올라간다'] },
    cautions: ['혼자 감당하다 고립된다', '자존심 때문에 도움을 거절한다', '책임 지출이 커서 자기 몫이 안 남는다'],
    compatible: ['ashlesha', 'ardra', 'uttara-bhadrapada'],
    caution: 'purva-ashadha',
  },
] as const
