import type { Nakshatra } from './types'

/**
 * 나크샤트라 1~9 (Ashwini ~ Ashlesha)
 *
 * 분류 필드(lord/gana/yoni/nadi/range)는 계산 엔진 테이블이 정본이다. validate.ts 가 대조한다.
 * 문안 톤: 구어체 + 구체적인 장면. 추상적인 성격 서술 대신 실제로 하는 행동을 짚는다.
 */
export const NAKSHATRAS_01_09: readonly Nakshatra[] = [
  {
    index: 0,
    key: 'ashwini',
    sanskrit: 'Ashwini',
    devanagari: 'अश्विनी',
    ko: '아쉬위니',
    archetype: '질주하는 말',
    tagline: '생각이 끝나기 전에 몸이 먼저 나가는 사람',
    lord: 'Ketu',
    deity: 'Ashwini Kumaras',
    deityKo: '아쉬윈 쌍둥이 — 신들의 의사',
    symbol: "Horse's head",
    symbolKo: '말의 머리',
    gana: 'Deva',
    yoni: 'Horse',
    yoniKo: '말',
    nadi: 'Adi',
    range: [0, 13.3333],
    rashi: ['양자리'],
    luckyColor: '핏빛 빨강',
    luckyColorHex: '#C0392B',
    gemstone: '캣츠아이',
    luckyNumber: 7,
    direction: '남서쪽',
    ratings: { wealth: 3, career: 4, love: 3, bond: 2, helper: 4 },
    keyword: '속도',
    copy: '남들이 아직 고민하고 있을 때 이미 시작해 있는 쪽이에요. 남들은 그걸 용기라고 하는데, 본인은 그냥 기다리는 게 답답했을 뿐이죠. 다치는 것도 빠른데 낫는 것도 빨라요.',
    ritual: '중요한 날 아침에 제일 먼저 한 일을 그날의 방향으로 삼으라고 해요.',
    strengths: ['남들 준비하는 동안 이미 한 바퀴 돌고 온다', '실패해도 다음 날이면 털고 일어난다', '아픈 사람 옆에 있으면 이상하게 기운을 준다'],
    shadows: ['80%쯤 왔을 때 갑자기 흥미가 식는다', '말이 앞서서 뱉고 나서 수습한다', '기다리라는 말을 제일 싫어한다'],
    career: ['의료·재활', '응급·구조', '스타트업 초기 멤버', '스포츠'],
    love: '먼저 좋아하고 먼저 말해요. 문제는 식는 것도 그 속도라, 상대가 이제 마음 열었을 때 이미 다른 데를 보고 있는 경우가 있어요.',
    wealth: '벌 때 확 벌고 쓸 때 확 써요. 통장에 남기려면 의지로는 안 되고, 손이 못 닿는 자동이체 구조부터 만들어야 해요.',
    publicSelf: '겁 없고 시원시원한 사람',
    trueSelf: '사실은 기다리는 게 무서운 사람',
    peak: { from: 28, to: 34, signals: ['안 하던 분야에서 먼저 연락이 온다', '몸 쓰는 일이 갑자기 즐거워진다', '오래 미룬 걸 하루 만에 끝낸다'] },
    cautions: ['80% 지점에서 손 놓는 버릇이 성과를 통째로 날린다', '말이 먼저 나가 관계를 잃는다', '쉬는 걸 게으름으로 착각한다'],
    compatible: ['pushya', 'uttara-phalguni', 'shravana'],
    caution: 'mula',
  },
  {
    index: 1,
    key: 'bharani',
    sanskrit: 'Bharani',
    devanagari: 'भरणी',
    ko: '바라니',
    archetype: '경계의 문지기',
    tagline: '다들 피하는 걸 결국 자기가 떠맡는 사람',
    lord: 'Venus',
    deity: 'Yama',
    deityKo: '야마 — 경계를 지키는 신',
    symbol: 'Womb, the gate of passage',
    symbolKo: '통과의 문',
    gana: 'Manushya',
    yoni: 'Elephant',
    yoniKo: '코끼리',
    nadi: 'Madhya',
    range: [13.3333, 26.6667],
    rashi: ['양자리'],
    luckyColor: '핏빛 자주',
    luckyColorHex: '#8E2749',
    gemstone: '다이아몬드',
    luckyNumber: 9,
    direction: '남동쪽',
    ratings: { wealth: 3, career: 4, love: 2, bond: 4, helper: 2 },
    keyword: '감당',
    copy: '아무도 안 하겠다고 할 때 결국 손 드는 쪽이에요. 하겠다고 했으면 끝을 보고요. 대신 그 무게를 아무한테도 말 안 하고 혼자 지고 다녀요.',
    ritual: '무언가를 끝낼 때는 붉은 꽃을 올리고 이름을 소리 내어 말하라고 해요.',
    strengths: ['맡은 건 무슨 일이 있어도 끝낸다', '남들이 못 버티는 구간을 그냥 버틴다', '옳고 그름의 선이 자기 안에 분명하다'],
    shadows: ['힘들다는 말을 끝까지 안 한다', '참다가 어느 날 한 번에 끝내버린다', '한 번 그은 선은 다시 안 지운다'],
    career: ['법·심사', '산부인과·장례 등 경계를 다루는 일', '조직 관리', '제작 총괄'],
    love: '마음 여는 데 오래 걸려요. 열고 나면 깊은데, 서운한 걸 그때그때 말 안 하고 모아뒀다가 한 번에 정리해버리는 게 문제예요.',
    wealth: '들어온 건 잘 지켜요. 다만 큰 결정을 너무 오래 재다가 기회가 지나간 뒤에 아쉬워하는 패턴이 반복돼요.',
    publicSelf: '든든하고 책임감 있는 사람',
    trueSelf: '혼자 다 지고 아무 말 안 하는 사람',
    peak: { from: 34, to: 41, signals: ['맡아달라는 부탁이 늘어난다', '오래 끌던 일이 한 번에 정리된다', '아랫사람이 생긴다'] },
    cautions: ['참다가 한 번에 끝내면 되돌릴 수 없다', '힘들다는 말을 안 해서 아무도 모른다', '선을 그으면 다시 안 지운다'],
    compatible: ['rohini', 'uttara-bhadrapada', 'anuradha'],
    caution: 'chitra',
  },
  {
    index: 2,
    key: 'krittika',
    sanskrit: 'Krittika',
    devanagari: 'कृत्तिका',
    ko: '크리티카',
    archetype: '불의 칼날',
    tagline: '속으로 이미 판정을 다 내려놓은 사람',
    lord: 'Sun',
    deity: 'Agni',
    deityKo: '아그니 — 불의 신',
    symbol: 'Sharp blade, flame',
    symbolKo: '날선 칼',
    gana: 'Rakshasa',
    yoni: 'Sheep',
    yoniKo: '양',
    nadi: 'Antya',
    range: [26.6667, 40],
    rashi: ['양자리', '황소자리'],
    luckyColor: '불꽃 주홍',
    luckyColorHex: '#E0512A',
    gemstone: '루비',
    luckyNumber: 1,
    direction: '동쪽',
    ratings: { wealth: 3, career: 5, love: 2, bond: 3, helper: 3 },
    keyword: '판별',
    copy: '처음 만난 자리에서 이미 그 사람이 어떤지 판단이 끝나 있어요. 그리고 그게 나중에 대체로 맞고요. 문제는 그 판단이 얼굴에 다 나온다는 거예요.',
    ritual: '결정을 앞둔 밤에는 촛불 하나를 끝까지 태우라고 해요.',
    strengths: ['진짜와 가짜를 빨리 구분한다', '기준을 세우면 자기부터 지킨다', '급할수록 판단이 또렷해진다'],
    shadows: ['맞는 말을 제일 아프게 한다', '완벽하게 못 할 것 같으면 아예 시작을 안 한다', '남의 대충을 못 넘긴다'],
    career: ['비평·편집', '품질·감사', '요리', '군·수사'],
    love: '애매한 사이를 못 견뎌요. "우리 뭐야?"를 먼저 묻는 쪽이고, 답이 흐리면 그 자리에서 정리해버리기도 해요.',
    wealth: '낭비가 거의 없고 판단도 정확해요. 다만 남 씀씀이를 평가하다가 사람을 잃는 일이 종종 생겨요.',
    publicSelf: '똑 부러지고 실력 있는 사람',
    trueSelf: '자기한테 제일 엄격한 사람',
    peak: { from: 30, to: 37, signals: ['평가하는 자리를 맡게 된다', '내 기준이 조직 기준이 된다', '싫은 소리 하는 게 일이 된다'] },
    cautions: ['맞는 말을 제일 아프게 해서 사람을 잃는다', '완벽하지 않으면 시작을 안 한다', '남의 대충을 못 넘겨 혼자 지친다'],
    compatible: ['rohini', 'uttara-ashadha', 'hasta'],
    caution: 'purva-phalguni',
  },
  {
    index: 3,
    key: 'rohini',
    sanskrit: 'Rohini',
    devanagari: 'रोहिणी',
    ko: '로히니',
    archetype: '붉은 수레',
    tagline: '버리는 게 없어서 결국 다 가지는 사람',
    lord: 'Moon',
    deity: 'Brahma',
    deityKo: '브라흐마 — 창조의 신',
    symbol: 'Ox cart, chariot',
    symbolKo: '소달구지',
    gana: 'Manushya',
    yoni: 'Snake',
    yoniKo: '뱀',
    nadi: 'Antya',
    range: [40, 53.3333],
    rashi: ['황소자리'],
    luckyColor: '진홍',
    luckyColorHex: '#B4213D',
    gemstone: '진주',
    luckyNumber: 2,
    direction: '북서쪽',
    ratings: { wealth: 5, career: 3, love: 4, bond: 4, helper: 3 },
    keyword: '결실',
    copy: '한 번 들인 건 잘 안 놔요. 물건도 사람도 자리도요. 27종 중에 가장 물질이 잘 붙는 자리인데, 그게 운이라기보다 안 버려서 쌓이는 쪽에 가까워요.',
    ritual: '보름에는 흰 음식을 올리고 고마운 걸 하나 적으라고 해요.',
    strengths: ['모으고 불리는 감각이 타고났다', '좋아하는 취향이 그대로 돈이 된다', '한자리에서 오래 버텨 결국 최고참이 된다'],
    shadows: ['정리해야 할 걸 못 버리고 끌고 간다', '가진 걸 티내지 않는데도 시샘을 산다', '변화를 제안하면 일단 방어부터 한다'],
    career: ['브랜드·디자인', '부동산·자산관리', '식음료', '농업·원예'],
    love: '오래 두고 보는 쪽이에요. 상대가 다른 사람이랑 잘 지내는 걸 보면 아무렇지 않은 척하면서 속으로는 다 세고 있어요.',
    wealth: '27종 중 재물이 제일 두터운 축이에요. 급하게 굴리지 말고 천천히 오래 두는 방식이 이 자리에 맞아요.',
    publicSelf: '여유 있고 취향 좋은 사람',
    trueSelf: '가진 걸 놓는 게 제일 무서운 사람',
    peak: { from: 32, to: 40, signals: ['취향으로 돈이 되는 제안이 온다', '오래 모은 것의 값이 갑자기 오른다', '자리를 오래 지킨 보상이 온다'] },
    cautions: ['정리할 걸 못 버려 자리가 좁아진다', '변화를 방어부터 해서 기회를 놓친다', '티 안 내도 시샘을 산다'],
    compatible: ['uttara-phalguni', 'anuradha', 'shravana'],
    caution: 'swati',
  },
  {
    index: 4,
    key: 'mrigashira',
    sanskrit: 'Mrigashira',
    devanagari: 'मृगशीर्ष',
    ko: '므리가쉬라',
    archetype: '찾아 헤매는 사슴',
    tagline: '이미 괜찮은데 더 좋은 게 있을까 봐 못 정하는 사람',
    lord: 'Mars',
    deity: 'Soma (Chandra)',
    deityKo: '소마 — 달의 신',
    symbol: "Deer's head",
    symbolKo: '사슴의 머리',
    gana: 'Deva',
    yoni: 'Snake',
    yoniKo: '뱀',
    nadi: 'Madhya',
    range: [53.3333, 66.6667],
    rashi: ['황소자리', '쌍둥이자리'],
    luckyColor: '은빛 회색',
    luckyColorHex: '#A9B2BC',
    gemstone: '레드 코럴',
    luckyNumber: 9,
    direction: '남쪽',
    ratings: { wealth: 3, career: 3, love: 4, bond: 2, helper: 3 },
    keyword: '탐색',
    copy: '장바구니에 담아두고 결제를 안 눌러요. 더 나은 게 있을 것 같아서요. 그런데 그 감각이 진짜 좋아서, 결국 찾아내긴 해요.',
    ritual: '길을 잃었다 싶을 땐 초승달에 향을 하나 피우라고 해요.',
    strengths: ['좋은 걸 남보다 먼저 알아본다', '낯선 데 던져놔도 금방 적응한다', '질문이 날카로워서 대화가 깊어진다'],
    shadows: ['정하는 걸 계속 미룬다', '가진 것에 만족하는 순간이 잘 안 온다', '탐색만 하다 시기를 놓친다'],
    career: ['리서치·기획', '여행·탐사', '트렌드 분석', '음악'],
    love: '알아가는 구간이 제일 즐거워요. 익숙해지면 설렘이 사라진 걸 관계 문제로 착각하기 쉬우니, 그건 원래 그런 거라고 알아두면 좋아요.',
    wealth: '정보로 버는 힘이 있어요. 다만 한군데 오래 못 둬서, 기다렸으면 컸을 걸 중간에 빼는 일이 잦아요.',
    publicSelf: '감각 좋고 아는 게 많은 사람',
    trueSelf: '정하는 게 제일 어려운 사람',
    peak: { from: 27, to: 34, signals: ['남들이 뭘 살지 물어보기 시작한다', '취향이 일이 되는 제안이 온다', '여행이나 이동 얘기가 나온다'] },
    cautions: ['탐색만 하다 시기를 놓친다', '가진 것에 만족하는 순간이 안 온다', '결정을 남에게 미룬다'],
    compatible: ['revati', 'hasta', 'punarvasu'],
    caution: 'uttara-ashadha',
  },
  {
    index: 5,
    key: 'ardra',
    sanskrit: 'Ardra',
    devanagari: 'आर्द्रा',
    ko: '아르드라',
    archetype: '폭풍의 눈물',
    tagline: '한 번 무너져보고 나서야 자기 얼굴을 찾는 사람',
    lord: 'Rahu',
    deity: 'Rudra',
    deityKo: '루드라 — 폭풍의 신',
    symbol: 'Teardrop',
    symbolKo: '눈물방울',
    gana: 'Manushya',
    yoni: 'Dog',
    yoniKo: '개',
    nadi: 'Adi',
    range: [66.6667, 80],
    rashi: ['쌍둥이자리'],
    luckyColor: '먹빛 초록',
    luckyColorHex: '#3B4A44',
    gemstone: '헤소나이트',
    luckyNumber: 4,
    direction: '남서쪽',
    ratings: { wealth: 2, career: 3, love: 3, bond: 3, helper: 4 },
    keyword: '전환',
    copy: '살면서 한 번은 크게 무너지는 구간을 지나요. 그리고 그 뒤의 사람이 진짜예요. 남의 고통을 알아보는 건 겪어봐서 아는 거고요.',
    ritual: '비 오는 날엔 못 한 말을 적어서 흘려보내라고 해요.',
    strengths: ['바닥까지 갔다가 다시 올라온다', '남이 못 하는 말을 대신 언어로 만든다', '기존 방식을 의심해서 새 길을 낸다'],
    shadows: ['기분의 낙차가 커서 본인이 제일 지친다', '괜찮다고 해놓고 혼자 앓는다', '자기를 몰아붙이는 게 습관이다'],
    career: ['상담·심리', '연구·분석', '재난·위기 대응', '글쓰기'],
    love: '깊고 격해요. 좋을 땐 아주 좋고 흔들릴 땐 크게 흔들려서, 그 진폭을 같이 견딜 수 있는 사람이어야 오래 가요.',
    wealth: '한 번 크게 잃고 한 번 크게 회복해요. 그 구간이 오기 전에 분산 구조를 짜두는 게 이 자리 최대 과제예요.',
    publicSelf: '깊이 있고 통찰이 있는 사람',
    trueSelf: '괜찮다고 해놓고 혼자 앓는 사람',
    peak: { from: 33, to: 40, signals: ['무너졌던 자리에서 제안이 온다', '내 얘기가 남에게 도움이 된다', '감정을 다루는 일이 들어온다'] },
    cautions: ['기분의 낙차로 본인이 제일 지친다', '자기를 몰아붙이는 게 습관이 된다', '한 번의 손실을 오래 붙잡는다'],
    compatible: ['shatabhisha', 'purva-bhadrapada', 'jyeshtha'],
    caution: 'purva-phalguni',
  },
  {
    index: 6,
    key: 'punarvasu',
    sanskrit: 'Punarvasu',
    devanagari: 'पुनर्वसु',
    ko: '푸나르바수',
    archetype: '돌아오는 화살',
    tagline: '끝났다 싶으면 다시 연락이 오는 사람',
    lord: 'Jupiter',
    deity: 'Aditi',
    deityKo: '아디티 — 무한의 어머니 신',
    symbol: 'Quiver of arrows',
    symbolKo: '화살통',
    gana: 'Deva',
    yoni: 'Cat',
    yoniKo: '고양이',
    nadi: 'Adi',
    range: [80, 93.3333],
    rashi: ['쌍둥이자리', '게자리'],
    luckyColor: '연노랑',
    luckyColorHex: '#EFD98A',
    gemstone: '옐로 사파이어',
    luckyNumber: 3,
    direction: '북동쪽',
    ratings: { wealth: 3, career: 3, love: 4, bond: 4, helper: 5 },
    keyword: '회복',
    copy: '끊어진 게 자꾸 다시 이어져요. 사람이든 일이든 돈이든요. 그래서 큰일 앞에서도 별로 안 불안한데, 그게 강점이자 약점이에요.',
    ritual: '멀리 다녀온 날엔 문 앞에서 한 번 숨을 고르고 들어가라고 해요.',
    strengths: ['다시 시작하는 데 거리낌이 없다', '같이 있으면 사람이 편해진다', '한 번 무너진 뒤에 오히려 넓어진다'],
    shadows: ['어떻게든 되겠지 하다가 같은 실수를 반복한다', '결정을 자꾸 다음 주로 미룬다', '정리해야 할 관계를 못 끊는다'],
    career: ['교육·강의', '출판', '여행·숙박', '커뮤니티 운영'],
    love: '헤어져도 다시 만나는 인연이 있어요. 돌아오는 게 운명인지 습관인지는 본인이 정해야 하는 부분이에요.',
    wealth: '잃어도 회복돼요. 문제는 그 믿음 때문에 관리가 느슨해지는 거라, 회복될 걸 알아도 안 잃는 게 낫죠.',
    publicSelf: '편안하고 사람 좋은 사람',
    trueSelf: '어떻게든 되겠지 하고 미루는 사람',
    peak: { from: 29, to: 36, signals: ['끊겼던 인연에서 연락이 온다', '가르치거나 알려주는 자리가 생긴다', '멀리 가는 얘기가 나온다'] },
    cautions: ['회복될 걸 알아서 관리가 느슨해진다', '정리할 관계를 못 끊는다', '결단을 다음 주로 미룬다'],
    compatible: ['pushya', 'revati', 'mrigashira'],
    caution: 'krittika',
  },
  {
    index: 7,
    key: 'pushya',
    sanskrit: 'Pushya',
    devanagari: 'पुष्य',
    ko: '푸쉬야',
    archetype: '스승의 연꽃',
    tagline: '남 챙기다 자기 밥은 식은 걸 먹는 사람',
    lord: 'Saturn',
    deity: 'Brihaspati',
    deityKo: '브리하스파티 — 신들의 스승',
    symbol: "Cow's udder, lotus",
    symbolKo: '젖을 내는 소, 연꽃',
    gana: 'Deva',
    yoni: 'Sheep',
    yoniKo: '양',
    nadi: 'Madhya',
    range: [93.3333, 106.6667],
    rashi: ['게자리'],
    luckyColor: '황금 노랑',
    luckyColorHex: '#D9A441',
    gemstone: '블루 사파이어',
    luckyNumber: 8,
    direction: '서쪽',
    ratings: { wealth: 4, career: 4, love: 3, bond: 5, helper: 5 },
    keyword: '양육',
    copy: '27종 중에 가장 상서로운 자리로 꼽혀요. 남을 키우는 데 재능이 있고, 키우다 보면 본인도 같이 커져요. 급하지 않은 게 이 사람의 힘이에요.',
    ritual: '목요일엔 누군가에게 한 끼를 사라고 해요.',
    strengths: ['옆에 있는 사람이 실제로 성장한다', '신뢰가 오래 쌓여서 잘 안 무너진다', '급한 상황에서도 흔들림이 적다'],
    shadows: ['자기 몫 챙기는 걸 제일 못 한다', '괜찮다고 하면서 뒤에서 다 떠안는다', '보호가 지나쳐서 상대를 답답하게 만든다'],
    career: ['교육·양육', '요식업', '의료·간호', '조직 문화·HR'],
    love: '돌보는 방식으로 사랑해요. 상대를 아이처럼 대하고 있진 않은지 가끔 확인해봐야 해요.',
    wealth: '꾸준히 쌓여요. 다만 남한테 쓰는 몫이 커서, 자기 몫을 먼저 떼어놓지 않으면 결국 안 남아요.',
    publicSelf: '따뜻하고 믿음직한 사람',
    trueSelf: '자기 몫은 늘 마지막인 사람',
    peak: { from: 31, to: 39, signals: ['키운 사람이 자리를 잡는다', '오래 쌓은 신뢰가 기회로 온다', '조직에서 사람을 맡게 된다'] },
    cautions: ['자기 몫을 먼저 안 떼면 안 남는다', '보호가 지나쳐 상대를 답답하게 한다', '거절을 못 해 일이 몰린다'],
    compatible: ['ashwini', 'punarvasu', 'anuradha'],
    caution: 'ashlesha',
  },
  {
    index: 8,
    key: 'ashlesha',
    sanskrit: 'Ashlesha',
    devanagari: 'आश्लेषा',
    ko: '아쉴레샤',
    archetype: '똬리 튼 뱀',
    tagline: '아무 말 안 했는데 이미 판을 다 읽은 사람',
    lord: 'Mercury',
    deity: 'Nagas',
    deityKo: '나가 — 뱀의 신들',
    symbol: 'Coiled serpent',
    symbolKo: '똬리 튼 뱀',
    gana: 'Rakshasa',
    yoni: 'Cat',
    yoniKo: '고양이',
    nadi: 'Antya',
    range: [106.6667, 120],
    rashi: ['게자리'],
    luckyColor: '심연의 검정',
    luckyColorHex: '#1F2933',
    gemstone: '에메랄드',
    luckyNumber: 5,
    direction: '북쪽',
    ratings: { wealth: 4, career: 4, love: 2, bond: 3, helper: 2 },
    keyword: '장악',
    copy: '회의에서 제일 말수가 적은데 결론은 이 사람 쪽으로 가요. 상대가 뭘 원하는지 먼저 알고, 필요한 순간까지 안 꺼내거든요.',
    ritual: '중요한 협상 전엔 검은 천 위에 물 한 잔을 올리라고 해요.',
    strengths: ['사람 속내를 정확히 읽는다', '설득이 아니라 배치로 이긴다', '위기에서 표정이 안 바뀐다'],
    shadows: ['속을 안 보여줘서 오해를 자초한다', '상대를 통제하려는 마음이 관계를 조인다', '서운한 걸 말 안 하고 거리를 둔다'],
    career: ['협상·영업', '정치·전략', '심리·상담', '보안·리스크'],
    love: '먼저 좋아한다고 말하는 게 세상에서 제일 어려운 쪽이에요. 상대가 먼저 말해주길 기다리다 타이밍을 놓치는 일이 많아요.',
    wealth: '정보와 사람으로 벌어요. 빌려준 돈이 오래 묶이는 일이 잦은데, 못 돌려받아도 말을 안 해서 더 그래요.',
    publicSelf: '조용하고 속을 알 수 없는 사람',
    trueSelf: '먼저 좋아한다고 말하는 게 제일 어려운 사람',
    peak: { from: 33, to: 41, signals: ['협상 자리를 맡게 된다', '판을 읽는 능력이 값으로 인정받는다', '비밀을 맡기는 사람이 늘어난다'] },
    cautions: ['속을 안 보여 오해가 쌓인다', '통제하려는 마음이 관계를 조인다', '빌려준 돈이 오래 묶인다'],
    compatible: ['jyeshtha', 'shatabhisha', 'revati'],
    caution: 'pushya',
  },
] as const
