import type { Nakshatra } from './types'

/** 나크샤트라 19~27 (Mula ~ Revati) */
export const NAKSHATRAS_19_27: readonly Nakshatra[] = [
  {
    index: 18,
    key: 'mula',
    sanskrit: 'Mula',
    devanagari: 'मूल',
    ko: '물라',
    archetype: '드러난 뿌리',
    tagline: '왜냐고 계속 묻다가 판을 뒤집는 사람',
    lord: 'Ketu',
    deity: 'Nirriti',
    deityKo: '니리티 — 해체의 여신',
    symbol: 'Bundle of tied roots',
    symbolKo: '묶인 뿌리 다발',
    gana: 'Rakshasa',
    yoni: 'Dog',
    yoniKo: '개',
    nadi: 'Adi',
    range: [240, 253.3333],
    rashi: ['사수자리'],
    luckyColor: '흙빛 갈색',
    luckyColorHex: '#6E4B2A',
    gemstone: '캣츠아이',
    luckyNumber: 7,
    direction: '남서쪽',
    ratings: { wealth: 2, career: 4, love: 2, bond: 2, helper: 3 },
    keyword: '근원',
    copy: '남들이 그냥 넘어가는 데서 혼자 멈춰서 왜냐고 물어요. 그러다 멀쩡히 굴러가던 걸 뜯어놓기도 하고요. 인생에 한 번은 뿌리째 옮겨 심는 구간이 있어요.',
    ritual: '큰 변화 앞에서는 오래 쓴 물건 하나를 정리하라고 해요.',
    strengths: ['끝까지 파고들어 진짜 원인을 찾는다', '당연하다고들 하는 걸 의심한다', '무너진 자리에서 다시 세울 줄 안다'],
    shadows: ['잘 굴러가는 것도 뜯어본다', '한번 아니다 싶으면 극단까지 간다', '답을 찾을 때까지 잠을 못 잔다'],
    career: ['연구·학문', '조사·저널리즘', '정신·영성 분야', '구조조정'],
    love: '깊이 들어가려고 해요. 상대의 지난 일까지 파헤치다가 알아서 좋을 것 없는 걸 알게 되는 경우가 있어요.',
    wealth: '한 번 크게 정리한 뒤에 자산 구조가 바뀌어요. 그 시기에 무리하게 벌리지만 않으면 돼요.',
  },
  {
    index: 19,
    key: 'purva-ashadha',
    sanskrit: 'Purva Ashadha',
    devanagari: 'पूर्वाषाढा',
    ko: '푸르바 아샤다',
    archetype: '거센 물',
    tagline: '결국 자기가 맞았다고 증명하고 마는 사람',
    lord: 'Venus',
    deity: 'Apas',
    deityKo: '아파 — 물의 여신들',
    symbol: 'Fan, winnowing basket',
    symbolKo: '부채',
    gana: 'Manushya',
    yoni: 'Monkey',
    yoniKo: '원숭이',
    nadi: 'Madhya',
    range: [253.3333, 266.6667],
    rashi: ['사수자리'],
    luckyColor: '물빛 파랑',
    luckyColorHex: '#2F6FA8',
    gemstone: '다이아몬드',
    luckyNumber: 6,
    direction: '남동쪽',
    ratings: { wealth: 4, career: 4, love: 4, bond: 3, helper: 4 },
    keyword: '설득',
    copy: '안 된다는 말을 들으면 오히려 눈이 반짝여요. 그 확신이 말이 돼서 사람을 움직이고, 실제로 되게 만드는 일이 많아요.',
    ritual: '중요한 발표 전엔 물을 한 잔 천천히 마시라고 해요.',
    strengths: ['말로 사람을 실제로 움직인다', '반대에 부딪힐수록 힘이 난다', '주변에 확신을 심어준다'],
    shadows: ['확신이 아집으로 굳는다', '졌다는 말을 입에 못 담는다', '반대 의견을 설득할 대상으로만 본다'],
    career: ['강연·연설', '마케팅·PR', '정치·조직화', '해운·수산'],
    love: '상대를 설득해서 관계를 만들어요. 문제는 그 뒤로도 계속 설득하려 든다는 거예요. 가끔은 그냥 들어주는 게 필요해요.',
    wealth: '설득해서 기회를 만들어요. 과신으로 한 곳에 몰아넣는 것만 조심하면 되는 자리예요.',
  },
  {
    index: 20,
    key: 'uttara-ashadha',
    sanskrit: 'Uttara Ashadha',
    devanagari: 'उत्तराषाढा',
    ko: '우타라 아샤다',
    archetype: '코끼리 엄니',
    tagline: '다들 나간 뒤에 혼자 남아서 이기는 사람',
    lord: 'Sun',
    deity: 'Vishvadevas',
    deityKo: '비슈바데바 — 만유의 신들',
    symbol: "Elephant's tusk",
    symbolKo: '코끼리의 엄니',
    gana: 'Manushya',
    yoni: 'Mongoose',
    yoniKo: '몽구스',
    nadi: 'Antya',
    range: [266.6667, 280],
    rashi: ['사수자리', '염소자리'],
    luckyColor: '황금빛 갈색',
    luckyColorHex: '#A5732B',
    gemstone: '블루 사파이어',
    luckyNumber: 1,
    direction: '동쪽',
    ratings: { wealth: 5, career: 5, love: 3, bond: 4, helper: 3 },
    keyword: '승리',
    copy: '27종 중에 가장 확실하게 끝내 이기는 자리예요. 시작이 느리고 알아주는 사람도 늦게 나타나는데, 한 번 얻은 건 안 빼앗겨요.',
    ritual: '큰일을 시작하는 날엔 아침 해를 한 번 보라고 해요.',
    strengths: ['끝까지 남아서 결과를 가져간다', '원칙이 분명해서 흔들리지 않는다', '신뢰가 늦게, 대신 크게 쌓인다'],
    shadows: ['한 번 정한 방식을 안 바꾼다', '남한테 맡기느니 자기가 한다', '인정이 늦다고 혼자 서운해한다'],
    career: ['공직·대기업', '장기 프로젝트', '법·회계', '연구'],
    love: '천천히 확실하게 가요. 상대는 그 속도를 무관심으로 오해할 수 있으니, 중간에 신호를 한 번은 줘야 해요.',
    wealth: '늦게 크게 와요. 30대 후반부터 자산 곡선이 눈에 띄게 꺾여 올라가는 자리예요.',
  },
  {
    index: 21,
    key: 'shravana',
    sanskrit: 'Shravana',
    devanagari: 'श्रवण',
    ko: '슈라바나',
    archetype: '열린 귀',
    tagline: '말은 안 했는데 다 듣고 다 기억하는 사람',
    lord: 'Moon',
    deity: 'Vishnu',
    deityKo: '비슈누 — 유지의 신',
    symbol: 'Ear',
    symbolKo: '귀',
    gana: 'Deva',
    yoni: 'Monkey',
    yoniKo: '원숭이',
    nadi: 'Antya',
    range: [280, 293.3333],
    rashi: ['염소자리'],
    luckyColor: '밝은 남색',
    luckyColorHex: '#3B5EA8',
    gemstone: '진주',
    luckyNumber: 2,
    direction: '북서쪽',
    ratings: { wealth: 4, career: 4, love: 3, bond: 4, helper: 4 },
    keyword: '경청',
    copy: '말하기보다 듣는 데서 힘이 나와요. 남들이 흘려보낸 얘기를 붙잡아뒀다가 정리해서 다시 꺼내주는데, 그게 이 사람 값어치예요.',
    ritual: '결정이 안 설 땐 아무 말도 하지 않고 하루를 보내라고 해요.',
    strengths: ['흩어진 정보를 하나로 꿴다', '몇 달 전 대화를 그대로 기억한다', '설명하면 상대가 진짜로 이해한다'],
    shadows: ['조언을 너무 많이 들어서 결정이 늦다', '자기 의견을 마지막까지 안 낸다', '남의 말에 하루 기분이 좌우된다'],
    career: ['교육·연구', '컨설팅·리서치', '미디어·기록', '통번역'],
    love: '들어주는 방식으로 사랑해요. 상대는 편한데, 정작 이 사람 얘기는 아무도 안 물어보는 상황이 생겨요.',
    wealth: '지식과 정보로 벌어요. 다만 주변 조언을 다 듣다가 결정 타이밍을 놓치는 게 반복되는 패턴이에요.',
  },
  {
    index: 22,
    key: 'dhanishta',
    sanskrit: 'Dhanishta',
    devanagari: 'धनिष्ठा',
    ko: '다니쉬타',
    archetype: '여덟 박의 북',
    tagline: '분위기 처지면 자기가 먼저 판을 까는 사람',
    lord: 'Mars',
    deity: 'Ashta Vasus',
    deityKo: '아쉬타 바수 — 여덟 원소의 신들',
    symbol: 'Drum',
    symbolKo: '북',
    gana: 'Rakshasa',
    yoni: 'Lion',
    yoniKo: '사자',
    nadi: 'Madhya',
    range: [293.3333, 306.6667],
    rashi: ['염소자리', '물병자리'],
    luckyColor: '은빛',
    luckyColorHex: '#B8BCC4',
    gemstone: '레드 코럴',
    luckyNumber: 9,
    direction: '남쪽',
    ratings: { wealth: 5, career: 4, love: 3, bond: 3, helper: 4 },
    keyword: '박자',
    copy: '이름부터가 "부유함"이라는 뜻이에요. 무리 안에서 박자를 만드는 역할을 맡게 되고, 그 박자를 따라 사람이랑 돈이 같이 붙어요.',
    ritual: '일이 안 풀릴 땐 음악을 틀고 한 곡을 끝까지 들으라고 해요.',
    strengths: ['판을 읽고 사람을 움직인다', '재물이 잘 붙는다', '실행 속도가 안 처진다'],
    shadows: ['속도 못 맞추는 사람을 답답해한다', '감정을 말로 옮기는 게 서툴다', '분위기 챙기다 자기 기분은 뒤로 민다'],
    career: ['음악·공연', '팀 리딩', '금융·투자', '제조 운영'],
    love: '리듬이 맞아야 편해요. 서운한 걸 말로 못 해서 갑자기 조용해지는 방식으로 표현하는데, 상대는 그걸 못 알아들어요.',
    wealth: '27종 중 재물이 잘 붙는 자리예요. 관건은 버는 게 아니라 기분 따라 나가는 지출을 구조로 막는 거예요.',
  },
  {
    index: 23,
    key: 'shatabhisha',
    sanskrit: 'Shatabhisha',
    devanagari: 'शतभिषा',
    ko: '샤타비샤',
    archetype: '백 개의 약',
    tagline: '혼자 있는 시간이 없으면 못 사는 사람',
    lord: 'Rahu',
    deity: 'Varuna',
    deityKo: '바루나 — 물과 우주 법칙의 신',
    symbol: 'Empty circle',
    symbolKo: '텅 빈 원',
    gana: 'Rakshasa',
    yoni: 'Horse',
    yoniKo: '말',
    nadi: 'Adi',
    range: [306.6667, 320],
    rashi: ['물병자리'],
    luckyColor: '청록',
    luckyColorHex: '#1F7A8C',
    gemstone: '헤소나이트',
    luckyNumber: 4,
    direction: '남서쪽',
    ratings: { wealth: 3, career: 4, love: 2, bond: 2, helper: 2 },
    keyword: '치유',
    copy: '사람 많은 데 다녀오면 반드시 혼자 있어야 회복돼요. 그 시간에 남들이 못 푼 문제를 풀어내고요. 비밀을 지키는 능력이 유별나요.',
    ritual: '지칠 땐 아무한테도 알리지 않고 하루를 비우라고 해요.',
    strengths: ['남이 손든 문제를 끝까지 붙잡는다', '한번 들은 비밀은 무덤까지 간다', '혼자서 깊이 파는 데 최적화돼 있다'],
    shadows: ['괜찮다며 연락을 끊는다', '도움을 받는 걸 빚으로 여긴다', '혼자 해결하려다 시기를 놓친다'],
    career: ['의료·연구', '데이터·보안', '심리·치유', '전기·화학'],
    love: '거리를 두면서 사랑해요. 상대는 그걸 식은 걸로 오해하니, "지금은 혼자 있어야 회복된다"는 걸 미리 설명해두는 게 좋아요.',
    wealth: '전문성으로 벌어요. 사람 통해 오는 기회가 적으니, 자기를 알릴 통로는 따로 만들어야 해요.',
  },
  {
    index: 24,
    key: 'purva-bhadrapada',
    sanskrit: 'Purva Bhadrapada',
    devanagari: 'पूर्व भाद्रपदा',
    ko: '푸르바 바드라파다',
    archetype: '외발의 불',
    tagline: '남들 안 하는 생각을 혼자 오래 하는 사람',
    lord: 'Jupiter',
    deity: 'Aja Ekapada',
    deityKo: '아자 에카파다 — 외발의 불꽃 신',
    symbol: 'Front legs of a funeral cot',
    symbolKo: '상여의 앞다리',
    gana: 'Manushya',
    yoni: 'Lion',
    yoniKo: '사자',
    nadi: 'Adi',
    range: [320, 333.3333],
    rashi: ['물병자리', '물고기자리'],
    luckyColor: '검은 자주',
    luckyColorHex: '#4A2545',
    gemstone: '옐로 사파이어',
    luckyNumber: 3,
    direction: '북동쪽',
    ratings: { wealth: 2, career: 3, love: 3, bond: 2, helper: 2 },
    keyword: '초월',
    copy: '평범한 기준으로는 설명이 잘 안 되는 사람이에요. 남들이 안 가는 지점까지 혼자 걸어 들어가고, 거기서 뭔가를 들고 나와요.',
    ritual: '마음이 무거운 밤엔 촛불을 켜고 아무 말 없이 앉아 있으라고 해요.',
    strengths: ['남이 못 보는 각도에서 본다', '두려움이 적어서 멀리까지 간다', '상식의 바깥에서 답을 가져온다'],
    shadows: ['기분의 낙차가 커서 주변이 예측을 못 한다', '이해받기를 일찍 포기한다', '한번 빠지면 일상이 무너진다'],
    career: ['철학·종교', '예술·창작', '연구', '위기·재난 분야'],
    love: '몰입이 극단적이에요. 좋을 땐 전부인데 식으면 갑자기 사라져서, 일상을 잡아줄 상대가 필요해요.',
    wealth: '평범한 경로로는 잘 안 풀려요. 자기만의 영역을 만들어야 그때부터 돈이 붙는 자리예요.',
  },
  {
    index: 25,
    key: 'uttara-bhadrapada',
    sanskrit: 'Uttara Bhadrapada',
    devanagari: 'उत्तर भाद्रपदा',
    ko: '우타라 바드라파다',
    archetype: '깊은 물의 뱀',
    tagline: '화낼 만한데 안 내서 오히려 무서운 사람',
    lord: 'Saturn',
    deity: 'Ahir Budhnya',
    deityKo: '아히르부드냐 — 심연의 뱀 신',
    symbol: 'Back legs of a funeral cot',
    symbolKo: '상여의 뒷다리',
    gana: 'Manushya',
    yoni: 'Cow',
    yoniKo: '소',
    nadi: 'Madhya',
    range: [333.3333, 346.6667],
    rashi: ['물고기자리'],
    luckyColor: '깊은 남색',
    luckyColorHex: '#243B6B',
    gemstone: '블루 사파이어',
    luckyNumber: 8,
    direction: '서쪽',
    ratings: { wealth: 4, career: 3, love: 4, bond: 5, helper: 4 },
    keyword: '침착',
    copy: '웬만해선 안 흔들려요. 화낼 상황에서도 목소리가 안 올라가고, 남 사정을 끝까지 들어줘요. 그 안정감 때문에 사람들이 계속 찾아와요.',
    ritual: '결정을 서두르게 될 땐 하룻밤을 반드시 넘기라고 해요.',
    strengths: ['감정이 오르내려도 티가 안 난다', '남을 함부로 판단하지 않는다', '오래 걸리는 일을 지겨워하지 않는다'],
    shadows: ['너무 참아서 자기가 뭘 원하는지 모른다', '변화를 받아들이는 데 시간이 오래 걸린다', '한계를 넘으면 조용히 관계를 끊는다'],
    career: ['상담·복지', '연구·학문', '종교·수행', '장기 자산 운용'],
    love: '깊고 조용해요. 상대는 반응이 없다고 느낄 수 있으니, 마음이 있다는 신호를 의식적으로 줘야 해요.',
    wealth: '천천히 안정적으로 쌓여요. 급한 기회는 대부분 놓치는데, 대신 크게 잃는 일도 거의 없어요.',
  },
  {
    index: 26,
    key: 'revati',
    sanskrit: 'Revati',
    devanagari: 'रेवती',
    ko: '레바티',
    archetype: '길잡이 물고기',
    tagline: '남 길만 찾아주다 자기 길을 늦추는 사람',
    lord: 'Mercury',
    deity: 'Pushan',
    deityKo: '푸샨 — 길을 지키는 신',
    symbol: 'Pair of fish',
    symbolKo: '두 마리 물고기',
    gana: 'Deva',
    yoni: 'Elephant',
    yoniKo: '코끼리',
    nadi: 'Antya',
    range: [346.6667, 360],
    rashi: ['물고기자리'],
    luckyColor: '연한 크림',
    luckyColorHex: '#F0E4CC',
    gemstone: '에메랄드',
    luckyNumber: 5,
    direction: '북쪽',
    ratings: { wealth: 3, career: 3, love: 4, bond: 4, helper: 5 },
    keyword: '인도',
    copy: '27종의 마지막 자리이자 다음으로 넘겨주는 자리예요. 길 잃은 사람이 자꾸 이 사람을 찾아와요. 마무리하고 배웅하는 데 능해요.',
    ritual: '누군가를 떠나보내는 날엔 문 앞까지 나가서 배웅하라고 해요.',
    strengths: ['옆에 있으면 사람이 안심한다', '마무리가 깔끔해서 뒷말이 없다', '상냥함이 실제로 무기가 된다'],
    shadows: ['거절을 못 해서 일이 계속 들어온다', '자기 차례를 계속 뒤로 미룬다', '받아야 할 돈을 말 못 하고 넘긴다'],
    career: ['여행·물류', '돌봄·복지', '교육', '중개·에이전시'],
    love: '상대를 편하게 해줘요. 정작 자기가 뭘 원하는지는 말한 적이 없어서, 상대가 영영 모르는 채로 지나가기도 해요.',
    wealth: '남을 돕는 과정에서 기회가 와요. 제값을 제때 청구하는 게 이 자리 최대 과제예요.',
  },
] as const
