import type { GrahaText, KootaText } from './types'

/** Navagraha — the nine planets, English copy. */
export const GRAHA_TEXT_EN: Record<string, GrahaText> = {
  Sun: {
    ko: 'Surya',
    weekday: 'Sunday',
    color: 'Ruby red',
    gemstone: 'Ruby',
    deityKo: 'Shiva — and Surya himself',
    direction: 'East',
    remedy: 'At sunrise, face east and pour out a little water.',
    keyword: 'Center',
    copy: "Eyes gather on you without you stepping forward. When you leave your seat, it shows immediately. You say it's a burden, and still you return to that seat.",
    strengths: ['Once you set a direction, people follow on their own', 'The heavier the responsibility, the steadier you are', 'You are recognized for results, not appearances'],
    shadows: ['In a seat with no recognition, you wither fast', 'Learning to bend takes you a long time', 'You hold onto the memory of being slighted'],
  },
  Moon: {
    ko: 'Chandra',
    weekday: 'Monday',
    color: 'Pearl white',
    gemstone: 'Pearl',
    deityKo: 'Parvati — the mother goddess',
    direction: 'Northwest',
    remedy: 'On a full-moon night, share something white to eat.',
    keyword: 'Intuition',
    copy: "You read the room before anyone speaks. Other people's feelings come in as if they were yours — which also means your day gets dragged around by other people's moods.",
    strengths: ["You pinpoint what people feel", 'You get stronger when there is someone to care for', 'You remember old things exactly as they were'],
    shadows: ["Someone else's mood takes over your whole day", 'You postpone refusing until you burn out', 'Pretending to be fine is a habit'],
  },
  Jupiter: {
    ko: 'Guru',
    weekday: 'Thursday',
    color: 'Saffron yellow',
    gemstone: 'Yellow sapphire',
    deityKo: 'Brahma — and the teacher Dakshinamurti',
    direction: 'Northeast',
    remedy: 'On Thursdays, serve someone something yellow to eat.',
    keyword: 'Trust',
    copy: 'People keep coming to ask you things. Your gift for teaching shows before your gift for learning, and your reputation becomes your wealth.',
    strengths: ['When you explain, people truly understand', 'Your long-range judgment is usually right', 'Your reputation brings in opportunities'],
    shadows: ['Words come first, execution comes late', "You get involved in others' business and neglect your own", 'You enjoy the adviser\'s seat a little too much'],
  },
  Rahu: {
    ko: 'Rahu',
    weekday: null,
    color: 'Smoke grey',
    gemstone: 'Hessonite',
    deityKo: 'Durga — the goddess riding a lion',
    direction: 'Southwest',
    remedy: 'At sunset on a Saturday, let black sesame seeds float away in running water.',
    keyword: 'Reversal',
    copy: "Your life turns over completely at least once. The road everyone takes strangely doesn't work for you; the way opens where nobody goes.",
    strengths: ['You settle first on a newly opened board', 'You see gaps others miss', 'One leap carries you far'],
    shadows: ["You can't stand a stable stretch", 'You push too hard and break what was already done', 'Impatience ruins your decisions'],
  },
  Mercury: {
    ko: 'Budha',
    weekday: 'Wednesday',
    color: 'Emerald green',
    gemstone: 'Emerald',
    deityKo: 'Vishnu — the preserver',
    direction: 'North',
    remedy: 'On Wednesdays, share green leafy vegetables.',
    keyword: 'Eloquence',
    copy: 'You tell the same story far more entertainingly. Words and writing become income directly, and making hard things easy is your specialty.',
    strengths: ['You sum up something complicated in one line', 'You have the edge at the negotiating table', 'You learn fast'],
    shadows: ['You move on before digging deep', 'People mistake you for lightweight', 'If it can be talked past, you talk past it'],
  },
  Venus: {
    ko: 'Shukra',
    weekday: 'Friday',
    color: 'Opal white',
    gemstone: 'Diamond',
    deityKo: 'Lakshmi — goddess of abundance',
    direction: 'Southeast',
    remedy: 'On Fridays, offer white flowers or incense.',
    keyword: 'Charm',
    copy: "You say you did nothing, and yet people approach first. You have an eye for beauty, and that taste becomes your work.",
    strengths: ['People attach to you even when you stand still', 'Your taste is your competitive edge', 'You soften the atmosphere'],
    shadows: ['Avoiding conflict, you let problems grow', 'Money leaks toward what you love', "You can't say the unwelcome thing"],
  },
  Ketu: {
    ko: 'Ketu',
    weekday: null,
    color: 'Dark brown',
    gemstone: "Cat's eye",
    deityKo: 'Ganesha — remover of obstacles',
    direction: null,
    remedy: "This planet's remedy is to show the way to someone who is lost.",
    keyword: 'Insight',
    copy: "It takes a long time for what's inside to show. You've already worked it all out but never bring it out. The people who recognize you tend to arrive late.",
    strengths: ['Depth comes from work you do alone', 'You see the essence faster than others', "You're quick to release attachment"],
    shadows: ['Skipping the explanation invites misunderstanding', 'You underrate yourself', 'You want to be recognized but never say so'],
  },
  Saturn: {
    ko: 'Shani',
    weekday: 'Saturday',
    color: 'Indigo black',
    gemstone: 'Blue sapphire',
    deityKo: 'Hanuman — and Yama',
    direction: 'West',
    remedy: 'On Saturdays, hand food to someone who is working.',
    keyword: 'Endurance',
    copy: 'You collect the result after everyone else has left. Slow at first, but what comes late lasts. Where others gave up is your starting line.',
    strengths: ['You see long work through to the end', 'Hard times make you harder', 'Your credit keeps building'],
    shadows: ["You're excessively strict only with yourself", 'You keep postponing enjoyment', "You never say it's hard"],
  },
  Mars: {
    ko: 'Mangala',
    weekday: 'Tuesday',
    color: 'Coral red',
    gemstone: 'Red coral',
    deityKo: 'Hanuman — and Kartikeya',
    direction: 'South',
    remedy: 'On Tuesdays, carry one red thing on you.',
    keyword: 'Drive',
    copy: "You're not afraid to start. You learn by throwing yourself in. But once burned, you remember that person for a long time.",
    strengths: ['You decide fast', "You're the first to move in a crisis", 'You try first, judge after'],
    shadows: ['Anger comes out first, regret follows', "You can't stand the waiting stretch", 'After a loss, you ache for days'],
  },
}

/** Ashtakoota — the eight kootas, English copy. */
export const KOOTA_TEXT_EN: Record<string, KootaText> = {
  varna: {
    ko: 'Values',
    measures: 'What each of you puts first in life',
    high: 'You value similar things, so you rarely clash on the big direction.',
    low: 'Your priorities differ, so what to do first needs negotiating every time.',
  },
  vashya: {
    ko: 'Pull',
    measures: 'The attraction between you and who leads',
    high: 'The pull is natural, with little fighting over who leads.',
    low: 'It easily becomes one person pulling the other along. Agree on how decisions get made.',
  },
  tara: {
    ko: 'Star Distance',
    measures: 'The flow of luck created by the distance between your birth stars',
    high: 'Things go well when you are together, and health stays stable.',
    low: "When one of you struggles, the other may shake too. Look after each other's condition.",
  },
  yoni: {
    ko: 'Instinct',
    measures: 'How well your bodies and instincts match (judged by 14 animal symbols)',
    high: 'Comfortable without words; time together restores you.',
    low: "Different rhythms can wear you out. Accepting each other's pace is the key.",
  },
  'graha-maitri': {
    ko: 'Planet Friendship',
    measures: 'Whether your ruling planets are friends or enemies',
    high: 'Your minds run on similar circuits, so conversation flows.',
    low: 'You think differently and hear the same words differently. Make a habit of checking.',
  },
  gana: {
    ko: 'Temperament',
    measures: 'Innate temperament type (Deva, Manushya, Rakshasa)',
    high: 'Your basic natures fit, so being together feels natural.',
    low: 'The temperament gap is large. Trying to fix the other person guarantees a clash. Start from difference.',
  },
  bhakoot: {
    ko: 'Household',
    measures: 'Stability and prosperity when living together',
    high: 'What you do together goes well, and daily life runs steadily.',
    low: 'Friction comes easily over practical matters. Agree in advance on money, housing, and family.',
  },
  nadi: {
    ko: 'Energy',
    measures: 'Constitution and energy type (Adi, Madhya, Antya)',
    high: "You fill in each other's missing energy.",
    low: 'Your energy types overlap. You tire out together, so take your rest at different times.',
  },
}

export const SCORE_BAND_TEXT_EN = [
  'A match that needs a lot of tuning',
  'A steady match',
  'A good match',
  'A rare match',
] as const
