import type { NakshatraText } from './types'

/**
 * Nakshatras 1–9 (Ashwini – Ashlesha), English copy.
 * Tone: plain, second person, concrete scenes over abstract traits.
 */
export const NAKSHATRA_TEXT_EN_01_09: Record<string, NakshatraText> = {
  ashwini: {
    ko: 'Ashwini',
    archetype: 'The Galloping Horse',
    tagline: 'Your body is already moving before the thought is finished',
    deityKo: 'The Ashvin twins — physicians of the gods',
    symbolKo: "A horse's head",
    yoniKo: 'Horse',
    rashi: ['Aries'],
    luckyColor: 'Blood red',
    gemstone: "Cat's eye",
    direction: 'Southwest',
    keyword: 'Speed',
    copy: "While everyone else is still deliberating, you've already started. People call it courage; you'd say waiting was simply unbearable. You get hurt fast, and you heal fast too.",
    ritual: 'On an important day, let the first thing you do that morning set the direction for the whole day.',
    strengths: ["You've finished a lap while others are still warming up", 'A failure is shaken off by the next morning', 'Sick people feel oddly better with you around'],
    shadows: ['Interest drops off suddenly around the 80% mark', 'Words come out first, cleanup comes later', 'Being told to wait is the thing you hate most'],
    career: ['Medicine & rehabilitation', 'Emergency & rescue', 'Early startup team', 'Sports'],
    love: {
      headline: 'First to fall, first to cool.',
      points: ['You approach without hesitation.', 'You cool at the same speed, so it misfires when the other person opens up late.', 'To make it last, you have to give yourself a reason to slow down.'],
    },
    wealth: {
      headline: 'Money that comes in bursts and leaves in bursts.',
      points: ['Short, intense earning streaks keep repeating.', "Willpower won't save it. You need a structure your hands can't reach.", 'You go in while others hesitate, and you get out first.'],
    },
    work: {
      headline: 'The one who starts things.',
      points: ['Your value shows where an early sprint matters.', 'Many short projects suit you better than one long one.', "You belong in the role that tries what nobody has tried."],
    },
    bond: "You're good at opening a relationship. Keeping it going is often done by the other person.",
    helper: 'The person who helped you in an emergency stays with you for years. Your benefactors come from those moments, not from networking.',
    publicSelf: 'Fearless and refreshingly direct',
    trueSelf: 'Actually afraid of waiting',
    cautions: ['Letting go at 80% wipes out the whole result', 'Words that run ahead cost you relationships', 'You mistake rest for laziness'],
    peak: {
      signals: ['A field you never worked in reaches out first', 'Physical work suddenly becomes fun', 'Something long postponed gets done in a day'],
      story: "Your forward drive is at its strongest, so opportunities arrive before you feel ready. In this window, sequence matters more than polish. Everything you raised your hand for first becomes your track record later.",
      actions: ['Revisit the offer you passed on while deliberating.', 'Start one thing, however small, under your own name.', "Don't skimp on your body. In this window, it's your capital."],
      miss: 'You gain speed but never bring in someone to finish, so the results scatter.',
    },
  },
  bharani: {
    ko: 'Bharani',
    archetype: 'The Gatekeeper',
    tagline: 'The one who ends up carrying what everyone else avoids',
    deityKo: 'Yama — guardian of the boundary',
    symbolKo: 'A gateway',
    yoniKo: 'Elephant',
    rashi: ['Aries'],
    luckyColor: 'Blood crimson',
    gemstone: 'Diamond',
    direction: 'Southeast',
    keyword: 'Bearing',
    copy: "When nobody volunteers, you're the one who raises a hand. And once you've said yes, you see it through. The catch: you tell no one how heavy it is and carry it alone.",
    ritual: 'When you finish something, offer a red flower and say its name out loud.',
    strengths: ['What you take on gets finished, whatever happens', 'You simply endure the stretch others can\'t', 'Your line between right and wrong is clear inside you'],
    shadows: ["You never say it's hard", 'You hold it in, then end it all at once one day', 'A line you\'ve drawn never gets erased'],
    career: ['Law & review', 'Work at life\'s boundaries — obstetrics, funeral care', 'Organizational management', 'Production lead'],
    love: {
      headline: 'Slow to open, shut in one motion.',
      points: ['Opening up takes you a long time, but once open, it runs deep.', 'You store up hurt and clear it all in one go.', 'Learning to speak up midway is what saves the relationship.'],
    },
    wealth: {
      headline: 'Money that stays once it arrives.',
      points: ['What you hold rarely leaks.', 'Your only loss comes from deliberating too long on a big decision and missing the moment.', 'Trust becomes your value when you manage other people\'s money.'],
    },
    work: {
      headline: 'The one who finishes things.',
      points: ['Taking on what nobody wants builds real skill.', 'That track record makes you irreplaceable.', 'The heavier the responsibility, the steadier you get.'],
    },
    bond: 'Once someone is in, they stay for years. But once you cut ties, you never look back.',
    helper: 'The person you carried through a hard time pulls you up later. It just takes a long time to be repaid.',
    publicSelf: 'Solid and responsible',
    trueSelf: 'Carrying everything alone and saying nothing',
    cautions: ["Holding it in and then ending it can't be undone", "Nobody knows because you never say it's hard", 'Lines you draw never get erased'],
    peak: {
      signals: ['More people ask you to take charge', 'A long-dragging matter resolves at once', 'You get people reporting to you'],
      story: 'The seat nobody else could hold comes to you. It is heavy, but once you pass through this window, you become hard to replace. The size of the responsibility becomes your value.',
      actions: ['Put in writing which things you will and will not take on.', 'Hand off at least one thing you are carrying alone.', 'Keep a record of the hard work. It becomes your evidence later.'],
      miss: "You never say it's hard, so nobody catches the moment to help.",
    },
  },
  krittika: {
    ko: 'Krittika',
    archetype: 'The Flame Blade',
    tagline: 'The verdict is already decided inside',
    deityKo: 'Agni — god of fire',
    symbolKo: 'A sharp blade',
    yoniKo: 'Sheep',
    rashi: ['Aries', 'Taurus'],
    luckyColor: 'Flame orange',
    gemstone: 'Ruby',
    direction: 'East',
    keyword: 'Judgment',
    copy: "By the end of a first meeting, you've already sized someone up. And you're usually right. The problem is that the verdict is written all over your face.",
    ritual: 'On the night before a decision, burn one candle all the way down.',
    strengths: ['You tell real from fake quickly', 'When you set a standard, you hold yourself to it first', 'The more urgent it gets, the clearer your judgment'],
    shadows: ['You say the true thing in the most painful way', "If it can't be perfect, you don't start", "You can't let other people's sloppiness slide"],
    career: ['Criticism & editing', 'Quality & audit', 'Cooking', 'Military & investigation'],
    love: {
      headline: 'Cannot stand an undefined relationship.',
      points: ['You are the one who asks "so what are we?" first.', 'If the answer is vague, you may end it on the spot.', 'Your demands are clear; learning to lower the bar is just as necessary.'],
    },
    wealth: {
      headline: 'Money with no waste.',
      points: ['The line between where to spend and where not to is sharp.', 'Your judgment is accurate, so big losses are rare.', "The real cost is losing people by judging how they spend."],
    },
    work: {
      headline: 'The one who judges.',
      points: ['You fit work that sets a standard and says no when something falls short.', 'Fields where the eye is the value — quality, audit, review — suit you.', "Not starting unless it can be perfect is your only bottleneck."],
    },
    bond: 'Few but deep. You let almost nobody in, so those who get in stay for years.',
    helper: 'A senior who recognized your skill reaches out at the decisive moment. Flattery never creates one.',
    publicSelf: 'Sharp and capable',
    trueSelf: 'Hardest on yourself',
    cautions: ['You lose people by saying true things painfully', "You don't start unless it can be perfect", "You can't let sloppiness slide and wear yourself out"],
    peak: {
      signals: ['You are put in an evaluating role', 'Your standard becomes the team standard', 'Saying the unwelcome thing becomes your job'],
      story: 'Your judgment turns directly into results. You get called in to review and sort out other people\'s work. This is when your standard becomes the organization\'s standard.',
      actions: ["Don't keep the standard only in words; write it down.", 'When you critique, point at the work, not the person.', 'Ship something unfinished at least once.'],
      miss: 'You lose people by saying the true thing in the most painful way.',
    },
  },
  rohini: {
    ko: 'Rohini',
    archetype: 'The Red Cart',
    tagline: 'Ends up with everything by never throwing anything away',
    deityKo: 'Brahma — the creator',
    symbolKo: 'An ox cart',
    yoniKo: 'Snake',
    rashi: ['Taurus'],
    luckyColor: 'Deep crimson',
    gemstone: 'Pearl',
    direction: 'Northwest',
    keyword: 'Harvest',
    copy: "You don't let go of what you've taken in — things, people, positions. Of all 27, this is the seat where material things stick best, and it's less luck than the fact that you never discard.",
    ritual: 'On the full moon, offer something white and write down one thing you are grateful for.',
    strengths: ['A born instinct for gathering and growing', 'Your taste turns directly into money', 'You stay in one place long enough to become the most senior'],
    shadows: ["You drag along what should have been cleared out", "You don't show off what you have, yet still draw envy", 'When change is proposed, you defend first'],
    career: ['Brand & design', 'Real estate & asset management', 'Food & beverage', 'Agriculture & horticulture'],
    love: {
      headline: 'Keeps and watches for the long run.',
      points: ["Once someone is in, you don't let go easily.", 'You act unbothered while counting everything inside.', "Leaving room for the other person is your task."],
    },
    wealth: {
      headline: 'Money that grows by accumulating.',
      points: ['Of all 27, this is where wealth sticks best.', 'Rushing it shrinks it. Leaving it alone is the right move.', 'Your taste becomes your asset.'],
    },
    work: {
      headline: 'The one who holds a position for the long run.',
      points: ['The longer you stay in one place, the more your value rises.', "Moving often means nothing accumulates for you.", 'Your taste and eye become your profession.'],
    },
    bond: "You keep people for the long haul, so relationships rarely break. The downside: little room for new people.",
    helper: 'Opportunity comes from people who share your taste. It starts with talking about what you love, not about work.',
    publicSelf: 'Relaxed, with excellent taste',
    trueSelf: 'Most afraid of letting go of what you have',
    cautions: ["Not clearing out what should go narrows your space", 'Defending against change costs you opportunities', 'You draw envy even without showing off'],
    peak: {
      signals: ['An offer to turn your taste into money', 'The value of what you gathered suddenly rises', 'A reward for holding your position'],
      story: 'The value of everything you stored up rises at once. Rather than starting something new, organizing what you already have and converting it into value is far more favorable. This is when taste becomes money.',
      actions: ['Find a way to turn stored assets and old work into value.', 'Gather the people who love your taste in one place.', 'Widen the seat you have instead of moving.'],
      miss: "There's no room for the new because you couldn't throw out what you were saving.",
    },
  },
  mrigashira: {
    ko: 'Mrigashira',
    archetype: 'The Searching Deer',
    tagline: "It's already fine, but you can't commit in case something better exists",
    deityKo: 'Soma — god of the moon',
    symbolKo: "A deer's head",
    yoniKo: 'Snake',
    rashi: ['Taurus', 'Gemini'],
    luckyColor: 'Silver grey',
    gemstone: 'Red coral',
    direction: 'South',
    keyword: 'Search',
    copy: "Items in the cart, checkout never pressed — there might be something better. But that instinct really is good, and in the end, you do find it.",
    ritual: 'When you feel lost, light one stick of incense on the night of a new moon.',
    strengths: ['You spot the good thing before others do', 'Drop you somewhere strange and you adapt fast', 'Your questions are sharp, so conversations go deep'],
    shadows: ['You keep postponing the decision', 'The moment of being satisfied with what you have rarely comes', 'You search so long the timing passes'],
    career: ['Research & planning', 'Travel & exploration', 'Trend analysis', 'Music'],
    love: {
      headline: 'The getting-to-know phase is the best part.',
      points: ['When the thrill fades, it\'s easy to mistake it for a problem in the relationship.', 'Knowing that is simply how it works makes things easier.', 'Building the fun that comes after familiarity is what makes it last.'],
    },
    wealth: {
      headline: 'Money earned through information.',
      points: ['Spotting the good thing first is itself your income.', "You rarely leave anything in one place long enough to compound.", 'Watch the pattern of pulling out midway from something that would have grown.'],
    },
    work: {
      headline: 'The one who finds things.',
      points: ['Recognizing the good thing first is your skill.', 'Research, planning, sourcing — work where the eye is the value.', 'Settling late makes your résumé look scattered; that is the weakness.'],
    },
    bond: 'You know many people broadly. The pity is moving on to the next before it deepens.',
    helper: 'Opportunity comes from chance encounters. The people you drift into matter more than planned meetings.',
    publicSelf: 'Great instincts, knows a lot',
    trueSelf: 'Finds deciding the hardest thing',
    cautions: ['Searching until the timing passes', 'Never feeling satisfied with what you have', 'Pushing decisions onto others'],
    peak: {
      signals: ['People start asking you what to buy', 'An offer to turn your taste into a job', 'Talk of travel or relocation comes up'],
      story: 'Everything you searched for narrows to one. Among interests scattered in every direction, one suddenly grows. This window is for choosing, not widening.',
      actions: ['Close two of the things you started and commit to one.', 'Put a deadline on the decision you have been circling.', 'Information that arrives through people is especially valuable now.'],
      miss: 'You let the window pass by not choosing, in case something better exists.',
    },
  },
  ardra: {
    ko: 'Ardra',
    archetype: 'The Storm\'s Tear',
    tagline: 'Finds their real face only after falling apart once',
    deityKo: 'Rudra — god of storms',
    symbolKo: 'A teardrop',
    yoniKo: 'Dog',
    rashi: ['Gemini'],
    luckyColor: 'Ink green',
    gemstone: 'Hessonite',
    direction: 'Southwest',
    keyword: 'Turning',
    copy: 'At some point in life you pass through a stretch where you fall apart completely. The person who comes after is the real one. You recognize other people\'s pain because you have been there.',
    ritual: 'On a rainy day, write down what you couldn\'t say and let it wash away.',
    strengths: ['You hit bottom and come back up', 'You put into words what others cannot say', 'You doubt the old way and cut a new path'],
    shadows: ['The mood swings exhaust you most of all', 'You say you\'re fine, then suffer alone', 'Driving yourself into the ground is a habit'],
    career: ['Counseling & psychology', 'Research & analysis', 'Disaster & crisis response', 'Writing'],
    love: {
      headline: 'Deep and intense.',
      points: ['Very good when it is good, badly shaken when it shakes.', 'It lasts only with someone who can hold that amplitude.', 'The relationships that survive a collapse together are the ones that remain.'],
    },
    wealth: {
      headline: 'Money lost big and recovered big.',
      points: ['You go through one large loss and one large recovery.', 'Spreading things out before that window is your biggest task.', 'The structure you build after the collapse is sturdier than before.'],
    },
    work: {
      headline: 'The one who rebuilds what fell.',
      points: ['Your value shows when you take over a situation others gave up on.', 'In a calm seat your skill goes unseen.', 'Your peak work is turning pain into language.'],
    },
    bond: 'You bond deeply and shake hard. Only those who can bear the amplitude stay.',
    helper: 'The person beside you when you collapsed stays for life. Those who came when you were flying rarely remain.',
    publicSelf: 'Deep and insightful',
    trueSelf: 'Says "I\'m fine" and suffers alone',
    cautions: ['The mood swings exhaust you most', 'Driving yourself becomes a habit', 'You hold onto one loss for too long'],
    peak: {
      signals: ['An offer comes from the place where you fell', 'Your story helps someone else', 'Work that deals with emotions arrives'],
      story: 'It comes by tearing down once and rebuilding. What looks like loss is actually clearing. Once through this window, the things built for other people\'s approval fall away and only what is truly yours remains.',
      actions: ['Decide what to quit first. Starting comes after.', 'Write down what you learned after the collapse.', 'Being beside someone in a hard season attracts opportunity.'],
      miss: 'You mistake the change for an accident and rush back to where you were.',
    },
  },
  punarvasu: {
    ko: 'Punarvasu',
    archetype: 'The Returning Arrow',
    tagline: 'Just when you think it\'s over, they get back in touch',
    deityKo: 'Aditi — mother of the infinite',
    symbolKo: 'A quiver of arrows',
    yoniKo: 'Cat',
    rashi: ['Gemini', 'Cancer'],
    luckyColor: 'Pale yellow',
    gemstone: 'Yellow sapphire',
    direction: 'Northeast',
    keyword: 'Return',
    copy: 'What gets cut keeps reconnecting — people, work, money. So you are rarely anxious even before big things, which is both your strength and your weakness.',
    ritual: 'On the day you return from far away, pause at the door and take one breath before entering.',
    strengths: ['No hesitation about starting over', 'People relax around you', 'You come back wider after each collapse'],
    shadows: ['"It\'ll work out somehow" repeats the same mistake', 'Decisions keep slipping to next week', 'You can\'t cut the relationships that need cutting'],
    career: ['Education & teaching', 'Publishing', 'Travel & hospitality', 'Community management'],
    love: {
      headline: 'Meets again after parting.',
      points: ['Broken connections often come back around.', 'You have to decide yourself whether to break the loop or continue it.', 'Your ease is a strength, and also complacency.'],
    },
    wealth: {
      headline: 'Money that comes back even when lost.',
      points: ['Money that leaves returns by another route.', 'That belief loosens your management — that is the problem.', 'Steady income attaches to teaching and explaining.'],
    },
    work: {
      headline: 'The one who starts again.',
      points: ['Teaching and explaining go well for you.', 'Going back to a field you once failed in and succeeding is common.', 'A broken career reconnects for this type.'],
    },
    bond: 'Cut ties reconnect. Those who will return, return without being held.',
    helper: 'Someone you helped years ago comes back with an opportunity.',
    publicSelf: 'Easygoing and warm',
    trueSelf: 'Postpones with "it\'ll work out somehow"',
    cautions: ['Knowing it will recover loosens your management', 'You can\'t cut the ties that should be cut', 'Decisions slip to next week'],
    peak: {
      signals: ['A message from a connection you thought was gone', 'A teaching or explaining role opens up', 'Talk of going somewhere far'],
      story: 'Connections and chances you thought were gone return. People you brushed past, projects you shelved, come back as offers. Reviving beats building from scratch in this window.',
      actions: ['Reach out first to former colleagues and clients.', 'Take the shelved project out again.', 'Retry a method that failed once, with only the conditions changed.'],
      miss: 'You wave off the returning opportunity as old news.',
    },
  },
  pushya: {
    ko: 'Pushya',
    archetype: 'The Teacher\'s Lotus',
    tagline: 'Eats their own meal cold from looking after everyone else',
    deityKo: 'Brihaspati — teacher of the gods',
    symbolKo: 'A cow\'s udder, a lotus',
    yoniKo: 'Sheep',
    rashi: ['Cancer'],
    luckyColor: 'Golden yellow',
    gemstone: 'Blue sapphire',
    direction: 'West',
    keyword: 'Nurture',
    copy: 'Counted the most auspicious of the 27. You have a gift for growing others, and you grow alongside them. Not being in a hurry is your power.',
    ritual: 'On Thursdays, buy someone a meal.',
    strengths: ['People next to you actually grow', 'Trust builds so long it rarely collapses', 'Little shaking even in urgent situations'],
    shadows: ['Claiming your own share is what you do worst', 'You say it\'s fine and shoulder everything behind the scenes', 'Overprotection smothers the other person'],
    career: ['Education & childcare', 'Restaurants', 'Medicine & nursing', 'Culture & HR'],
    love: {
      headline: 'Loves by taking care.',
      points: ['Looking after someone is how you show affection.', 'Check now and then whether you are treating them like a child.', 'Learning to receive makes the relationship far easier.'],
    },
    wealth: {
      headline: 'Money that accumulates steadily.',
      points: ['Not fast, but the flow never stops.', 'You spend so much on others that you must set your own share aside first.', 'Long-built trust returns late as a big opportunity.'],
    },
    work: {
      headline: 'The one who grows people.',
      points: ['Slow work — education, care, organizational culture — suits you.', 'People beside you actually grow.', 'Your only loss is being clumsy about claiming your own results.'],
    },
    bond: 'People who come in rarely leave. But the person who looks after you arrives late.',
    helper: 'Someone you raised settles into a position and repays you. That is this type\'s asset.',
    publicSelf: 'Warm and dependable',
    trueSelf: 'Always last in line for their own share',
    cautions: ['Nothing is left unless you take your share first', 'Overprotection smothers others', 'Inability to refuse piles work on you'],
    peak: {
      signals: ['Someone you raised finds their place', 'Long-built trust turns into an opportunity', 'You are put in charge of people'],
      story: 'What you invested in others returns to you. The people you looked after settle in, and from those seats they call for you. This is when your gift for people becomes actual results.',
      actions: ['Keep in touch with the people you raised.', 'Take on one job that teaches or organizes.', 'Make at least one clear request for your own share.'],
      miss: 'You look after everyone first and cannot raise your hand when your turn comes.',
    },
  },
  ashlesha: {
    ko: 'Ashlesha',
    archetype: 'The Coiled Serpent',
    tagline: 'Said nothing, but already read the whole board',
    deityKo: 'The Nagas — serpent deities',
    symbolKo: 'A coiled serpent',
    yoniKo: 'Cat',
    rashi: ['Cancer'],
    luckyColor: 'Abyss black',
    gemstone: 'Emerald',
    direction: 'North',
    keyword: 'Command',
    copy: 'You speak least in the meeting, yet the conclusion drifts your way. You know what the other side wants before they do, and you hold it until the moment it is needed.',
    ritual: 'Before an important negotiation, set a glass of water on a black cloth.',
    strengths: ['You read what people really think', 'You win by positioning, not persuasion', 'Your face does not change in a crisis'],
    shadows: ['Hiding your inner self invites misunderstanding', 'The urge to control tightens relationships', 'You distance yourself instead of saying you are hurt'],
    career: ['Negotiation & sales', 'Politics & strategy', 'Psychology & counseling', 'Security & risk'],
    love: {
      headline: 'Cannot say it first.',
      points: ['Saying "I like you" first is the hardest thing in the world.', 'You wait for them to say it and miss the timing.', 'Misunderstandings pile up because you keep your inside hidden.'],
    },
    wealth: {
      headline: 'Money earned through people.',
      points: ['Information and relationships are your income channels.', 'Money you lend stays tied up for a long time, more so because you never bring it up.', 'You have the power to create value at the negotiating table.'],
    },
    work: {
      headline: 'The one who arranges the board.',
      points: ['Strong at untangling tangled interests.', 'Negotiation, strategy, and risk management suit you.', 'You produce results through positioning, not persuasion.'],
    },
    bond: 'Few relationships, kept for years. But your hidden inside sometimes exhausts the other person first.',
    helper: 'Someone who watched quietly steps forward at the decisive moment. They move before you ask.',
    publicSelf: 'Quiet and unreadable',
    trueSelf: 'Finds saying "I like you" first the hardest thing',
    cautions: ['Hidden feelings pile up misunderstandings', 'The urge to control tightens relationships', 'Money you lend stays tied up'],
    peak: {
      signals: ['You are handed the negotiation', 'Your ability to read the board is recognized as valuable', 'More people entrust you with secrets'],
      story: 'Your ability to read the board turns into power. You come to influence decisions from a seat that is not visible. This is a window where much is gained without a sound.',
      actions: ['Decide the order in which you reveal what you know.', 'Try a role where you connect and separate people.', 'Secure real authority over a visible title.'],
      miss: 'You read everything and say nothing, so the credit goes to someone else.',
    },
  },
}
