import type { NakshatraText } from './types'

/** Nakshatras 10–18 (Magha – Jyeshtha), English copy. */
export const NAKSHATRA_TEXT_EN_10_18: Record<string, NakshatraText> = {
  magha: {
    ko: 'Magha',
    archetype: 'The Empty Throne',
    tagline: 'Still remembers the moment of being slighted years later',
    deityKo: 'The Pitris — ancestral spirits',
    symbolKo: 'A throne',
    yoniKo: 'Rat',
    rashi: ['Leo'],
    luckyColor: 'Antique gold',
    gemstone: 'Ruby',
    direction: 'Southwest',
    keyword: 'Legacy',
    copy: 'Your life runs on inheriting the seat of those before you. Authority sits naturally on you, so you are treated as the elder without stepping forward. But a memory of being treated carelessly never erases.',
    ritual: 'Before a big decision, bring to mind the name of someone who has passed.',
    strengths: ['You carry the weight a position requires, naturally', 'You know how to handle tradition and form', 'You look after your own people to the end'],
    shadows: ['When not shown respect, your heart closes on the spot', 'You cannot let go of the past and keep replaying it', 'You accept losses to save face'],
    career: ['Public service & administration', 'Family business succession', 'Heritage & archives', 'Protocol & ceremony'],
    love: {
      headline: 'Opens only when respected.',
      points: ['Feeling honored matters more than anything.', 'One careless remark keeps you unwell for days.', 'You never say why you were hurt.'],
    },
    wealth: {
      headline: 'Money that is passed down.',
      points: ['Assets come in the form of inheritance or handover.', 'Most leaks are face-saving expenses. Plug those and you are fine.', 'As your position rises, money follows.'],
    },
    work: {
      headline: 'The one who inherits.',
      points: ['Taking over and growing what exists suits you better than building new.', 'Fields with form — public service, family business, heritage — fit.', 'Authority sits so naturally on you that the seat feels right.'],
    },
    bond: 'You stay long with those who show respect. Those who treated you carelessly get quietly removed.',
    helper: 'A senior singles you out and pulls you up. Someone notices without you stepping forward.',
    publicSelf: 'Dignified and mature',
    trueSelf: 'Still remembers the slight from years ago',
    cautions: ['Face-saving expenses keep leaking', 'Replaying the past makes you miss the present', 'You close on the spot when not respected'],
    peak: {
      signals: ['Talk of a seat to inherit comes up', 'A senior singles you out', 'You are put in charge of form and ceremony'],
      story: 'This is the window where your name gets attached. You take a front-facing seat — representative, senior — and inheriting or succeeding comes up. The memory of being overlooked turns into fuel.',
      actions: ['Do not decline the front-facing seat.', 'Take the role of sorting out old family or organizational matters.', 'Make one piece of work that carries your name.'],
      miss: 'You focus on being recognized and miss the substance.',
    },
  },
  'purva-phalguni': {
    ko: 'Purva Phalguni',
    archetype: 'The Midday Garden',
    tagline: 'So serious about having fun that people gather around',
    deityKo: 'Bhaga — god of enjoyment and one\'s share',
    symbolKo: 'Front legs of a bed',
    yoniKo: 'Rat',
    rashi: ['Leo'],
    luckyColor: 'Soft pink',
    gemstone: 'Diamond',
    direction: 'Southeast',
    keyword: 'Delight',
    copy: 'Knowing how to rest is your talent. Set up a gathering and people come, and the sense that makes the room enjoyable actually produces money.',
    ritual: 'On Fridays, buy one thing you love and give it to yourself.',
    strengths: ['You have the sense to make a room enjoyable', 'Your gift for staging and decorating works in practice', 'Giving comes naturally, so you have few enemies'],
    shadows: ['Hard things get postponed first', 'When it is fun, the plan slides', 'You spend according to mood'],
    career: ['Performance & entertainment', 'Fashion & beauty', 'Hospitality', 'Events'],
    love: {
      headline: 'Enjoys the romance itself.',
      points: ['Time together has to be fun.', 'When the fun fades, so does the feeling.', 'You constantly need new delight to build together.'],
    },
    wealth: {
      headline: 'Money earned while enjoying.',
      points: ['Your sense for gathering people actually produces income.', 'Spending by mood leaves nothing.', 'Only setting money aside the moment it arrives works for you.'],
    },
    work: {
      headline: 'The one who gathers people.',
      points: ['Your sense for creating gatherings becomes the job itself.', 'Planning, staging, hospitality suit you.', 'The habit of postponing hard work is your only brake.'],
    },
    bond: 'Wide and cheerful. Because you never share the hard stuff, depth takes time.',
    helper: 'Someone you simply had fun with brings an unexpected opportunity. It works better than work relationships.',
    publicSelf: 'Bright and fun to be around',
    trueSelf: 'Laughs off the hard stuff',
    cautions: ['Spending by mood leaves nothing', 'Hard work keeps getting postponed', 'When the fun fades, so does the relationship'],
    peak: {
      signals: ['Someone asks you to host', 'Your taste becomes content', 'Work comes in through people'],
      story: 'People flock to you and opportunity follows. What you started for fun turns into money. Doing what you love outperforms anything forced.',
      actions: ['Sell something you did as a hobby, at least once.', 'Host a gathering yourself.', 'Invest in what is visible. It gains value.'],
      miss: 'Carried away by the mood, you postpone the invoices and contracts.',
    },
  },
  'uttara-phalguni': {
    ko: 'Uttara Phalguni',
    archetype: 'The Vow Ring',
    tagline: 'Takes the loss to keep a promise once made',
    deityKo: 'Aryaman — god of contracts and friendship',
    symbolKo: 'Back legs of a bed',
    yoniKo: 'Cow',
    rashi: ['Leo', 'Virgo'],
    luckyColor: 'Bright orange',
    gemstone: 'Ruby',
    direction: 'East',
    keyword: 'Covenant',
    copy: 'You keep your word, even when circumstances change and it costs you. That is why people who have worked with you come back.',
    ritual: 'On the day you make a promise, share the same food with the other person.',
    strengths: ['Trust you give lasts for years', 'You are especially strong in partnership and collaboration', 'You attach no conditions to helping'],
    shadows: ['Recovering from betrayal takes years', 'You keep promises already broken by the other side', 'You are bound too tightly to form and procedure'],
    career: ['Legal & contracts', 'Consulting', 'Matchmaking & brokerage', 'Public service'],
    love: {
      headline: 'Dates with marriage in mind.',
      points: ['You give stability and demand the same weight in return.', 'You clash with people who want something light.', 'Once bound, you rarely cut it.'],
    },
    wealth: {
      headline: 'Money that grows only when earned together.',
      points: ['Partnership and collaboration change your income bracket completely.', 'Trying to do everything alone slows you down.', 'Trust is your asset; once built, it lasts.'],
    },
    work: {
      headline: 'The one who works with others.',
      points: ['Work where trust is the asset — partnership, contracts, brokerage — suits you.', 'Results are far bigger as a pair than alone.', 'You are strong at handling form and procedure.'],
    },
    bond: 'Once bound, it lasts for years. Of the 27, this is the type whose ties break least.',
    helper: 'Someone you have known for years introduces the decisive seat. Old connections beat new ones.',
    publicSelf: 'Upright and keeps their word',
    trueSelf: 'Still keeping a promise the other side already broke',
    cautions: ['Recovery from betrayal takes years', 'Tied to form, you lose flexibility', 'You keep promises knowing they cost you'],
    peak: {
      signals: ['Talk of partnership or contracts comes up', 'You are asked to mediate', 'An old relationship turns into work'],
      story: 'The value of promises kept for years returns. A reputation for being trustworthy turns into real seats and contracts. Not flashy, but this is your most solid climb.',
      actions: ['Turn relationships that ran on word into contracts.', 'Find something to build with someone you have worked with for years.', 'Raise your terms at least once.'],
      miss: 'You leave losing terms in place out of loyalty.',
    },
  },
  hasta: {
    ko: 'Hasta',
    archetype: 'The Hand That Makes',
    tagline: 'Instead of explaining, just makes it and shows you',
    deityKo: 'Savitar — the sun as craftsman',
    symbolKo: 'An open hand',
    yoniKo: 'Buffalo',
    rashi: ['Virgo'],
    luckyColor: 'Bright green',
    gemstone: 'Pearl',
    direction: 'Northwest',
    keyword: 'Craft',
    copy: 'You have the gift of pulling what is in your head out through your hands. Fiddly work never bores you, and that precision becomes your price.',
    ritual: 'At dawn, wash your hands and write one line about what you will make that day.',
    strengths: ['The skill gap shows in the details', 'You turn a thought into a physical thing right away', 'You loosen a room with a joke'],
    shadows: ['Caught in details, you miss the deadline', 'You cannot stand the sloppiness of other people\'s work', 'You keep replacing words with objects'],
    career: ['Crafts & manufacturing', 'Design & development', 'Medical procedures', 'Cooking & baking'],
    love: {
      headline: 'Expresses through action.',
      points: ['Instead of saying it, you make something and look after them.', 'The other person often wants to hear it in words.', 'Check whether you are replacing expression with objects only.'],
    },
    wealth: {
      headline: 'Money from your fingertips.',
      points: ['Skill and precision become your price directly.', 'Income jumps when you work under your own name rather than for someone else.', 'What you make brings in the next job.'],
    },
    work: {
      headline: 'The one who makes.',
      points: ['Precision at your fingertips is your value.', 'Your income bracket changes when you put your name on it.', 'What you make brings the next job.'],
    },
    bond: 'You express through action rather than words, so it takes time for the other person to notice.',
    helper: 'People find you after seeing what you made. The work comes before the selling.',
    publicSelf: 'Skilled and meticulous',
    trueSelf: 'Keeps making things instead of saying them',
    cautions: ['Caught in details, you miss deadlines', 'Unable to stand sloppiness, you do it all yourself', 'You express only through objects'],
    peak: {
      signals: ['A chance to put your name on something', 'You are handed what others could not make', 'You are priced by your detail'],
      story: 'What comes from your hands gets paid. Your skill shows without explanation, and what you have made brings people to you. This is when craft beats title.',
      actions: ['Gather what you have made and show it outside.', 'Take on one job that teaches your craft.', 'This is the time to raise your rate. Raise it.'],
      miss: 'You stay glued to making, so nobody does the telling.',
    },
  },
  chitra: {
    ko: 'Chitra',
    archetype: 'The Artisan\'s Jewel',
    tagline: 'Stops at the mirror one more time before going out',
    deityKo: 'Vishvakarma — architect of the gods',
    symbolKo: 'A shining jewel',
    yoniKo: 'Tiger',
    rashi: ['Virgo', 'Libra'],
    luckyColor: 'Jewel teal',
    gemstone: 'Red coral',
    direction: 'South',
    keyword: 'Staging',
    copy: 'Give the same thing to anyone, and it looks better once you touch it. You polish yourself like a work of art, too. That sense becomes your profession.',
    ritual: 'Before an important occasion, fix exactly one thing in the mirror.',
    strengths: ['You raise finish quality one level above everyone else', 'You have an eye for designing structure', 'The air changes when you walk in'],
    shadows: ['Money spent on appearance keeps growing', 'You cannot stand being compared', 'You avoid the occasion, saying you are not ready'],
    career: ['Architecture & interiors', 'Branding & art direction', 'Jewelry & fashion', 'Film & video'],
    love: {
      headline: 'Appearance matters.',
      points: ['You feel hurt when the other person gets comfortable and stops dressing up.', 'It is awkward to say why, so you keep it inside.', 'Give yourself time to look at the inside.'],
    },
    wealth: {
      headline: 'Money earned through taste.',
      points: ['The finish you show is your rate.', 'Spending follows your taste too, so you need a ceiling.', 'The trap is money for appearances growing without end.'],
    },
    work: {
      headline: 'The one who shows.',
      points: ['Raising the finish one level is your skill.', 'Fields where taste is the price — branding, space, video — suit you.', 'Your portfolio is your network.'],
    },
    bond: 'Many are drawn to you; few stay long. The cause is boredom once a relationship gets comfortable.',
    helper: 'Someone who recognized your work opens the next stage. Your portfolio is your network.',
    publicSelf: 'Polished and eye-catching',
    trueSelf: 'Finds being compared hardest to bear',
    cautions: ['Spending on appearance keeps growing', 'You avoid chances, saying you are not ready', 'You store up hurt toward those who got comfortable'],
    peak: {
      signals: ['You are given a stage', 'Your taste gets a price', 'Work arrives with your name in front'],
      story: 'What is seen becomes real power. "Great taste" turns into commissions, and your seat and your people visibly improve. The stage grows.',
      actions: ['Invest properly in how your work looks.', 'When invited to a big occasion, just go.', 'Choose one signature piece to put your name on.'],
      miss: 'You keep postponing the reveal while measuring the finish.',
    },
  },
  swati: {
    ko: 'Swati',
    archetype: 'Bud of the Wind',
    tagline: 'Cannot ask for help even when it is hard',
    deityKo: 'Vayu — god of wind',
    symbolKo: 'A sprout swaying in the wind',
    yoniKo: 'Buffalo',
    rashi: ['Libra'],
    luckyColor: 'Sky blue',
    gemstone: 'Hessonite',
    direction: 'Southwest',
    keyword: 'Independence',
    copy: 'Leaning on someone is what you hate most. You sway but do not snap, and in the end you make your own place by your own strength. Freedom is your condition.',
    ritual: 'On a windy day, open the window and say out loud what you want to do.',
    strengths: ['You produce results alone', 'You lean to no side', 'Drop you anywhere and you survive'],
    shadows: ['"Help me" never comes out', 'When you feel tied down, you end the relationship', 'Doing it alone takes longer than it needs to'],
    career: ['Solo business & freelance', 'Trade & distribution', 'Diplomacy & mediation', 'Aviation & transport'],
    love: {
      headline: 'Cools when confined.',
      points: ['"Let\'s talk more often" is easy to hear as control.', 'You fit a partner who respects separate space.', 'Adjusting to that difference is the key.'],
    },
    wealth: {
      headline: 'Money you run alone.',
      points: ['Earning for yourself and managing for yourself fits you.', 'You like forms you can pull out anytime, so long-term assets come late.', 'Inside an organization, you tend to be under-rewarded for your skill.'],
    },
    work: {
      headline: 'The one who runs it alone.',
      points: ['Solo business or freelance structures fit you best.', 'Inside an organization you tend to be under-rated.', 'Drop you anywhere and you survive.'],
    },
    bond: 'The distance you keep is what makes it last. Relationships glued together daily end faster.',
    helper: 'Someone would step in if you just asked, but you never ask, so the chance passes.',
    publicSelf: 'Free and at home anywhere',
    trueSelf: '"Help me" never comes out',
    cautions: ['Doing it alone takes longer than needed', 'Feeling tied down, you end relationships', 'Loving liquidity, your long-term assets come late'],
    peak: {
      signals: ['Results from work you did alone', 'You are asked to mediate', 'Talk of relocation or going abroad'],
      story: 'The conditions for moving alone fall into place. Independence, a job change, your own business come up naturally. This is when switching affiliation costs the least.',
      actions: ['If you have been thinking about going independent, move within this window.', 'Spread your clients instead of concentrating them.', 'Say "help me" at least once.'],
      miss: 'Trying to do it alone, you let every chance for help pass.',
    },
  },
  vishakha: {
    ko: 'Vishakha',
    archetype: 'The Triumphal Gate',
    tagline: 'Cannot sleep until what was decided is finished',
    deityKo: 'Indra & Agni — gods of victory and fire',
    symbolKo: 'A triumphal arch',
    yoniKo: 'Tiger',
    rashi: ['Libra', 'Scorpio'],
    luckyColor: 'Golden orange',
    gemstone: 'Yellow sapphire',
    direction: 'Northeast',
    keyword: 'Tenacity',
    copy: 'Once you set a goal, you see nothing else. You start late and still arrive. The problem is that by the time you arrive, a few people next to you are gone.',
    ritual: 'On the day you set a goal, write the reason in one sentence and keep it where you can see it.',
    strengths: ['You never let go of a goal once you grab it', 'Competition brings you alive', 'Rejected, you knock again'],
    shadows: ['Absorbed in the goal, you lose people', 'When results are late, you get sharp with those around you', 'You treat rest as waste'],
    career: ['Sales & performance teams', 'Sports & competitive fields', 'Founding a company', 'R&D'],
    love: {
      headline: 'Approaches like a conquest.',
      points: ['Your focus until you win someone is remarkable.', 'The test is whether you keep it up after winning.', 'You last with someone who looks at the same goal.'],
    },
    wealth: {
      headline: 'Money earned in concentrated bursts.',
      points: ['You build big through concentrated investment.', 'Impatient with diversification, you hit a window of big loss.', 'Put the goal in numbers and you actually reach it.'],
    },
    work: {
      headline: 'The one who competes.',
      points: ['Your best shows where results are visible in numbers.', 'You start late and still end up ahead.', 'Losing people along the way is your only cost.'],
    },
    bond: 'You last with those who look at the same goal. At a different pace, you drift apart fast.',
    helper: 'A rival who recognized you later becomes a colleague. Your enemies become your benefactors.',
    publicSelf: 'Clear goals and drive',
    trueSelf: 'Treats rest as waste',
    cautions: ['Absorbed in the goal, you lose people', 'When results lag, you get sharp', 'Impatient with diversification, you lose big'],
    peak: {
      signals: ['You are placed in competition', 'What you started late starts to pull ahead', 'A chance to show results in numbers'],
      story: 'What you held onto to see through comes to fruition. The final gate of something long prepared lies in this window. Win once here and the whole board changes.',
      actions: ['Reduce your goals to one and postpone the rest.', 'Do not avoid the seat where competition happens.', 'Plan the rest you will take after the result, in advance.'],
      miss: 'You never decided what to do after winning, and feel hollow.',
    },
  },
  anuradha: {
    ko: 'Anuradha',
    archetype: 'The Friend\'s Lotus',
    tagline: 'Drop them somewhere strange and they still gather people',
    deityKo: 'Mitra — god of friendship and pacts',
    symbolKo: 'A lotus',
    yoniKo: 'Deer',
    rashi: ['Scorpio'],
    luckyColor: 'Deep violet',
    gemstone: 'Blue sapphire',
    direction: 'West',
    keyword: 'Bonding',
    copy: 'Go somewhere knowing no one, and within six months people have gathered around you. You bind by trust, not rank, and those you struggled alongside stay for life.',
    ritual: 'On the new moon, contact one person you are grateful to.',
    strengths: ['The people you gather rarely scatter', 'You endure hard seasons alongside others', 'The stranger the environment, the stronger you get'],
    shadows: ['You devote so much to relationships that nothing is left of you', 'You share your feelings only much later', 'Unable to refuse, work piles up'],
    career: ['Team & organizational leadership', 'International business', 'Community & nonprofit', 'Planning'],
    love: {
      headline: 'Deepens slowly.',
      points: ['Your heart was decided long ago, but expressing it comes late.', 'There is a long stretch where the other person thinks nothing is happening.', 'Once decided, it lasts.'],
    },
    wealth: {
      headline: 'Money that people bring.',
      points: ['One of the few types where money spent on relationships actually comes back.', 'Opportunity comes from those you struggled alongside.', 'Trying to earn alone keeps the scale small.'],
    },
    work: {
      headline: 'The one who leads the team.',
      points: ['The stranger the environment, the more your skill shows.', 'Building from scratch — abroad, a new organization — suits you.', 'The people you gather rarely scatter.'],
    },
    bond: 'The people you gather rarely scatter. Of the 27, this is the type with the thickest gift for connection.',
    helper: 'Those you struggled alongside stay for life. Far stronger than easy acquaintances.',
    publicSelf: 'Gets along with everyone and gathers people',
    trueSelf: 'Shares feelings only much later',
    cautions: ['Devoted to relationships, nothing is left of you', 'Unable to refuse, work piles up', 'Late expression invites misunderstanding'],
    peak: {
      signals: ['You settle into a strange place', 'Someone asks you to lead a team', 'Opportunity from those you struggled alongside'],
      story: 'This window works through people. The relationships you built harden into a team or organization, and you settle quickly even in a strange place. Together beats alone by far.',
      actions: ['Formally bind the people you will work with.', 'Do not refuse work that takes you outside or abroad.', 'Take the role of connecting people in the middle.'],
      miss: 'Looking after relationships, you never settle your own share of the stake.',
    },
  },
  jyeshtha: {
    ko: 'Jyeshtha',
    archetype: 'The Eldest\'s Amulet',
    tagline: 'Steps to the front without showing how hard it is',
    deityKo: 'Indra — king of the gods',
    symbolKo: 'A round amulet',
    yoniKo: 'Deer',
    rashi: ['Scorpio'],
    luckyColor: 'Deep russet',
    gemstone: 'Emerald',
    direction: 'North',
    keyword: 'Protection',
    copy: 'Whatever your actual birth order, you end up playing the eldest. Responsibility comes first, people to protect appear, and you never show the weight.',
    ritual: 'On a hard day, wrap a red thread around your wrist.',
    strengths: ['You stand first in the dangerous place', 'You carry those under you to the end', 'Fast and accurate judgment'],
    shadows: ['Carrying it alone, you become isolated at some point', 'Pride makes you refuse help', 'Asked if you are okay, you always say yes'],
    career: ['Organizational management', 'Security & audit', 'Crisis response', 'Licensed professions'],
    love: {
      headline: 'Loves by protecting.',
      points: ['Standing in front to shield them is your affection.', 'If they remain only someone to protect, you never become equals.', 'Learning to lean changes the relationship.'],
    },
    wealth: {
      headline: 'Big responsibility, big outflow.',
      points: ['Earning is not bad, but the outgoing share is large.', 'Without a rule to secure your own share first, this never changes.', 'As the seat you hold grows, so does income.'],
    },
    work: {
      headline: 'The one who takes responsibility.',
      points: ['Work that requires standing in front — crisis management, running an organization — suits you.', 'Fast, accurate judgment makes you stronger under pressure.', 'Beware of isolation from carrying it alone.'],
    },
    bond: 'You connect by protecting. Relationships of equal leaning feel awkward to you.',
    helper: 'Someone you shielded shields you later. Until then, you have to hold out alone.',
    publicSelf: 'Solid and stands in front',
    trueSelf: 'Always says "I\'m fine" when asked',
    cautions: ['Carrying it alone, you become isolated', 'Pride makes you refuse help', 'Responsibility spending leaves nothing for you'],
    peak: {
      signals: ['You are handed a crisis', 'More people report to you', 'You rise to a seat of responsibility'],
      story: 'The front-facing seat comes. Responsibility grows, but so does the power to decide. You never show strain, so those around you have no idea how heavy it is.',
      actions: ['Clearly demand authority to match what you carry.', 'Raise your successor in this window.', 'Put time alone on your calendar.'],
      miss: 'You carry it all and then drop it all at once.',
    },
  },
}
