import type { NakshatraText } from './types'

/** Nakshatras 19–27 (Mula – Revati), English copy. */
export const NAKSHATRA_TEXT_EN_19_27: Record<string, NakshatraText> = {
  mula: {
    ko: 'Mula',
    archetype: 'Deep Roots',
    tagline: 'Keeps asking why until the whole board flips',
    deityKo: 'Nirriti — goddess of dissolution',
    symbolKo: 'A bundle of roots',
    yoniKo: 'Dog',
    rashi: ['Sagittarius'],
    luckyColor: 'Earth brown',
    gemstone: "Cat's eye",
    direction: 'Southwest',
    keyword: 'Origin',
    copy: 'Where others just move on, you stop alone and ask why. Sometimes you take apart something that was running fine. Once in life there is a stretch where you get transplanted, roots and all.',
    ritual: 'Before a big change, clear out one object you have used for a long time.',
    strengths: ['You dig to the end and find the real cause', 'You doubt what everyone calls obvious', 'You know how to rebuild where things collapsed'],
    shadows: ['You take apart even what runs fine', 'Once you decide something is wrong, you go to the extreme', 'You cannot sleep until you find the answer'],
    career: ['Research & academia', 'Investigation & journalism', 'Spiritual & mental fields', 'Restructuring'],
    love: {
      headline: 'Wants to know everything.',
      points: ["You try to dig into the other person's past.", 'Sometimes you learn things that were better left unknown.', 'Practice leaving some things unknown.'],
    },
    wealth: {
      headline: 'Money that changes after one overhaul.',
      points: ['After a big clearing, your asset structure changes completely.', 'Just do not overextend during that period.', 'You are valued for solving problems others could not.'],
    },
    work: {
      headline: 'The one who rebuilds from scratch.',
      points: ['Work that touches the roots — research, investigation, restructuring — suits you.', 'Problems nobody could solve get passed to you.', 'The habit of dismantling what works is your risk.'],
    },
    bond: 'You bond deeply, but with few. Some find your digging too much.',
    helper: 'Someone who asked the same questions you did becomes your benefactor. It works even across fields.',
    publicSelf: 'Digs deep and honest',
    trueSelf: "Can't sleep until the answer is found",
    cautions: ['You take apart what runs fine', 'Once decided it is wrong, you go to extremes', 'You overextend during the clearing period'],
    peak: {
      signals: ['You are asked to redesign the board', 'A problem nobody solved gets passed to you', 'After one clearing, the structure changes'],
      story: 'This window overturns everything from the root. The way you did things changes entirely, and the process looks like loss. But only after this window do you play on your own board instead of someone else\'s.',
      actions: ['Start by asking again why it has been done this way.', 'Begin one thing you learn from the ground up.', 'Relationships that need ending, end in this window.'],
      miss: 'You only overturn and put no effort into building anew.',
    },
  },
  'purva-ashadha': {
    ko: 'Purva Ashadha',
    archetype: 'Fierce Water',
    tagline: 'Ends up proving they were right after all',
    deityKo: 'Apas — goddesses of water',
    symbolKo: 'A fan',
    yoniKo: 'Monkey',
    rashi: ['Sagittarius'],
    luckyColor: 'Water blue',
    gemstone: 'Diamond',
    direction: 'Southeast',
    keyword: 'Persuasion',
    copy: 'Being told "it can\'t be done" makes your eyes light up. That conviction turns into words that move people, and often it actually happens.',
    ritual: 'Before an important presentation, drink a glass of water slowly.',
    strengths: ['Your words actually move people', 'Opposition gives you energy', 'You plant conviction in those around you'],
    shadows: ['Conviction hardens into stubbornness', 'You cannot say the words "I lost"', 'You see opposing views only as targets to persuade'],
    career: ['Lecturing & public speaking', 'Marketing & PR', 'Politics & organizing', 'Shipping & fisheries'],
    love: {
      headline: 'Starts by persuading.',
      points: ['You pull the other person in and build the relationship.', 'If you keep persuading after that, they get tired.', 'Sometimes you just need to listen.'],
    },
    wealth: {
      headline: 'Money made by persuasion.',
      points: ['You create opportunities out of nothing with words.', 'Just beware of overconfidence that piles everything in one place.', 'People attach first, then money follows.'],
    },
    work: {
      headline: 'The one who persuades.',
      points: ['Your best shows in sales, PR, and organizing.', 'You have the power to push through opposition.', 'The moment conviction hardens into stubbornness is the danger.'],
    },
    bond: 'You start by pulling people in. If you keep persuading after that, they get tired.',
    helper: 'Those persuaded by your conviction follow you to the end. People attach before numbers.',
    publicSelf: 'Convinced and well-spoken',
    trueSelf: 'Cannot say the words "I lost"',
    cautions: ['Conviction hardens into stubbornness', 'You treat opposing views only as targets', 'Overconfidence piles everything in one place'],
    peak: {
      signals: ['A seat to speak in front opens up', 'You push something through opposition', 'A role gathering people comes'],
      story: 'This is when persuasion lands. Results prove you were right, and your words and writing move people. What you push comes back in equal measure.',
      actions: ['Step into the seat where you sell with words.', 'Keep a record of your arguments.', 'Scale up one level while the flow is good.'],
      miss: 'Absorbed in winning, you lose the people who would have come with you.',
    },
  },
  'uttara-ashadha': {
    ko: 'Uttara Ashadha',
    archetype: 'The Elephant\'s Tusk',
    tagline: 'Wins by being the only one left after everyone leaves',
    deityKo: 'The Vishvadevas — the universal gods',
    symbolKo: 'An elephant\'s tusk',
    yoniKo: 'Mongoose',
    rashi: ['Sagittarius', 'Capricorn'],
    luckyColor: 'Golden brown',
    gemstone: 'Blue sapphire',
    direction: 'East',
    keyword: 'Victory',
    copy: 'Of the 27, this is the seat that most surely wins in the end. You start slow and recognition comes late, but what you gain is never taken away.',
    ritual: 'On the day you start something big, look at the morning sun once.',
    strengths: ['You stay to the end and take the result', 'Clear principles keep you unshaken', 'Trust builds late, but big'],
    shadows: ['You never change a method once decided', 'You would rather do it yourself than delegate', 'You quietly resent that recognition is slow'],
    career: ['Public service & large corporations', 'Long-term projects', 'Law & accounting', 'Research'],
    love: {
      headline: 'Slow and certain.',
      points: ['Your slow pace is easily mistaken for indifference.', 'You need to send a signal at least once along the way.', 'Once decided, you do not waver.'],
    },
    wealth: {
      headline: 'Money that comes late and big.',
      points: ['From your late thirties, your asset curve bends visibly upward.', 'Slow at first, but what you gain is never taken away.', 'Long games favor you over short ones.'],
    },
    work: {
      headline: 'The one who stays.',
      points: ['Public service, licensed professions, and long projects fit.', 'Short contests actually work against you.', 'You stay to the end and take the result.'],
    },
    bond: 'Slow to deepen, hard to break. Send a signal so the other person does not misread your pace.',
    helper: 'Someone who watched you stay to the end gives the decisive push. It comes late, but big.',
    publicSelf: 'Principled and trustworthy',
    trueSelf: 'Quietly hurt that recognition is slow',
    cautions: ['You never change a method once decided', 'You do it yourself rather than delegate, and wear out', 'You are hurt by being called slow'],
    peak: {
      signals: ['Work you did for years gets its price', 'You are the only one left', 'Talk of inheriting a position comes up'],
      story: 'It comes late but lasts. This is the window where you stay after everyone else drops out and take it in the end. The seat you gain here is not easily shaken.',
      actions: ['Choose work that lasts over work that ends quickly.', 'Secure the conditions for endurance — money and stamina — first.', 'Focus on work that will remain under your name.'],
      miss: 'You endure too long and miss the moment to make it known.',
    },
  },
  shravana: {
    ko: 'Shravana',
    archetype: 'The Listening Moon',
    tagline: 'Says nothing, hears everything, remembers all of it',
    deityKo: 'Vishnu — the preserver',
    symbolKo: 'An ear',
    yoniKo: 'Monkey',
    rashi: ['Capricorn'],
    luckyColor: 'Bright navy',
    gemstone: 'Pearl',
    direction: 'Northwest',
    keyword: 'Listening',
    copy: 'Your power comes from listening rather than speaking. You hold onto what others let slip, organize it, and hand it back — and that is your value.',
    ritual: 'When you cannot decide, spend a day without saying a word.',
    strengths: ['You thread scattered information into one', 'You remember a conversation from months ago exactly', 'When you explain, people really understand'],
    shadows: ['You take in so much advice that decisions come late', 'You withhold your own opinion until the last moment', "Other people's words set your mood for the day"],
    career: ['Education & research', 'Consulting & research', 'Media & records', 'Interpretation & translation'],
    love: {
      headline: 'Loves by listening.',
      points: ['The other person is comfortable, but nobody asks about you.', 'You need to share your own story for the relationship to balance.', 'Your memory is good, so you look after the small things.'],
    },
    wealth: {
      headline: 'Money earned from what you know.',
      points: ['Knowledge and information become income directly.', 'Listening to all the advice, you keep missing the decision point.', 'You are valued where you organize and pass things on.'],
    },
    work: {
      headline: 'The one who organizes and passes on.',
      points: ['Value comes from education, research, and records.', 'Threading scattered information into one is your skill.', 'Giving your own opinion late is your only weakness.'],
    },
    bond: 'People gather because you listen. You have to build separately the people who will listen to you.',
    helper: 'Someone you listened to brings decisive information. Information is opportunity.',
    publicSelf: 'Listens well and knows a lot',
    trueSelf: 'Nobody ever asks about them',
    cautions: ['Listening to all the advice, you miss the decision', 'You withhold your opinion to the last', "Other people's words set your mood"],
    peak: {
      signals: ['Work that organizes and explains arrives', 'Records or materials become valuable', 'A teaching seat opens'],
      story: 'What you heard becomes money. Stored information and relationships find use all at once, and a seat to sell what you learned appears. You are often called in as adviser.',
      actions: ['Organize what you know and put it out.', 'Spend money on learning. It comes back immediately.', 'In important rooms, listen first and speak later.'],
      miss: 'You hear everything and give no opinion, so you leave no presence.',
    },
  },
  dhanishta: {
    ko: 'Dhanishta',
    archetype: 'Drums of Abundance',
    tagline: 'Gets the party going when the mood drops',
    deityKo: 'The Ashta Vasus — gods of the eight elements',
    symbolKo: 'A drum',
    yoniKo: 'Lion',
    rashi: ['Capricorn', 'Aquarius'],
    luckyColor: 'Silver',
    gemstone: 'Red coral',
    direction: 'South',
    keyword: 'Rhythm',
    copy: 'The name itself means "wealthiest." You take on the role of setting the rhythm in a group, and people and money attach to that rhythm together.',
    ritual: 'When things are stuck, play music and listen to one song all the way through.',
    strengths: ['You read the board and move people', 'Wealth sticks to you', 'Your execution never lags'],
    shadows: ["You lose patience with people who can't keep pace", 'Putting feelings into words is awkward for you', 'Tending the mood, you push your own feelings aside'],
    career: ['Music & performance', 'Team leadership', 'Finance & investment', 'Manufacturing operations'],
    love: {
      headline: 'Comfortable only in rhythm.',
      points: ['You cannot say you are hurt and go quiet.', 'The other person does not read that signal.', 'Practice putting feelings into words.'],
    },
    wealth: {
      headline: 'Money that sticks.',
      points: ['The name itself means wealth.', 'The issue is not earning but spending that follows your mood.', 'Income is largest when you are the one running the board.'],
    },
    work: {
      headline: 'The one who runs the board.',
      points: ['Work where rhythm matters — running a team, finance, performance — suits you.', 'People and money attach to you together.', 'Impatience with those who cannot keep pace is the problem.'],
    },
    bond: 'You last with people who match your pace. Impatient with slower ones, you sometimes lose them.',
    helper: 'Those who set up a game with you do the next one too. A rhythm matched once lasts.',
    publicSelf: 'Lifts the mood and runs the show',
    trueSelf: 'Goes quiet instead of saying they are hurt',
    cautions: ["You lose patience with those who can't keep pace", 'Mood spending is large', 'Tending the mood, you push your own feelings aside'],
    peak: {
      signals: ['A seat running a team arrives', 'A board where money gathers comes into view', 'You meet someone who matches your pace'],
      story: 'This is when the rhythm lands. Everything you set up hits its timing, and people and money attach together. Assets grow visibly.',
      actions: ['Open one more channel for income.', 'Take the front seat on stage or at gatherings.', 'Decide in advance where incoming money will go.'],
      miss: 'You grow the board but bring in nobody to manage it.',
    },
  },
  shatabhisha: {
    ko: 'Shatabhisha',
    archetype: 'The Night Healer',
    tagline: 'Cannot live without time alone',
    deityKo: 'Varuna — god of waters and cosmic law',
    symbolKo: 'An empty circle',
    yoniKo: 'Horse',
    rashi: ['Aquarius'],
    luckyColor: 'Teal',
    gemstone: 'Hessonite',
    direction: 'Southwest',
    keyword: 'Healing',
    copy: 'After a crowd, you must be alone to recover. In that time you solve what others could not. Your ability to keep a secret is exceptional.',
    ritual: 'When exhausted, clear a whole day without telling anyone.',
    strengths: ['You hold onto problems others gave up on, to the end', 'A secret once heard goes to the grave', 'Built for digging deep alone'],
    shadows: ['You cut contact, saying you are fine', 'You treat receiving help as a debt', 'Trying to solve it alone, you miss the timing'],
    career: ['Medicine & research', 'Data & security', 'Psychology & healing', 'Electrical & chemical'],
    love: {
      headline: 'Loves at a distance.',
      points: ['You need time alone to recover.', 'The other person mistakes it for cooling off.', 'Explaining in advance solves most of it.'],
    },
    wealth: {
      headline: 'Money earned through expertise.',
      points: ['In a field you dug deep, you become irreplaceable.', 'Few opportunities come through people, so build a separate channel.', 'It takes long to become known, but once known, it is stable.'],
    },
    work: {
      headline: 'The one who digs deep.',
      points: ['Research, medicine, data, and security fit.', 'You hold problems others abandoned to the end.', 'With no channel to be known, opportunities come late.'],
    },
    bond: 'You keep distance and last long. Frequent meetings feel like a burden.',
    helper: 'Someone who recognized your expertise connects you quietly. You have to build your own channel to be known.',
    publicSelf: 'Expert and unshakable',
    trueSelf: 'Cannot live without time alone',
    cautions: ['You cut contact saying you are fine', 'You treat help as a debt', 'With no channel to be known, chances come late'],
    peak: {
      signals: ['A problem others gave up on lands with you', 'Your expertise makes your name', 'What you dug alone becomes valuable'],
      story: 'This is the window for fixing. Value comes from untangling what is broken or blocked. What you held alone for a long time comes out as results.',
      actions: ['Dig into one long-postponed problem to the end.', 'Secure time to work alone. That is where the results come from.', 'Fix your health and sleep in this window.'],
      miss: 'Trying to solve everything alone, you make no one to tell.',
    },
  },
  'purva-bhadrapada': {
    ko: 'Purva Bhadrapada',
    archetype: 'Fire on One Leg',
    tagline: 'Thinks alone, for a long time, what others never think',
    deityKo: 'Aja Ekapada — the one-footed fire god',
    symbolKo: 'Front legs of a funeral cot',
    yoniKo: 'Lion',
    rashi: ['Aquarius', 'Pisces'],
    luckyColor: 'Black purple',
    gemstone: 'Yellow sapphire',
    direction: 'Northeast',
    keyword: 'Transcendence',
    copy: 'You are hard to explain by ordinary standards. You walk alone to places others do not go, and come back with something.',
    ritual: 'On a heavy night, light a candle and sit without a word.',
    strengths: ['You see from angles others cannot', 'Little fear, so you go far', 'You bring answers from outside common sense'],
    shadows: ['Your mood swings so much that people cannot predict you', 'You give up early on being understood', 'Once absorbed, daily life collapses'],
    career: ['Philosophy & religion', 'Art & creation', 'Research', 'Crisis & disaster fields'],
    love: {
      headline: 'Extreme immersion.',
      points: ['When it is good, it is everything; when it cools, you suddenly vanish.', 'You need a partner who anchors daily life.', 'Relationships where you are understood are rare, but the one you have is deep.'],
    },
    wealth: {
      headline: 'Money that will not come by the ordinary road.',
      points: ['On the path everyone takes, you do not get what your skill deserves.', 'Only after you build your own domain does it attach.', 'Once settled, you have almost no competitors.'],
    },
    work: {
      headline: 'The seat nobody else takes.',
      points: ['Work that handles extremes — philosophy, art, crisis response — suits you.', 'On the ordinary path, your skill goes unrewarded.', 'Once settled, you have almost no competitors.'],
    },
    bond: 'Being understood is rare. But even one relationship runs deep.',
    helper: 'The person who listened to your thinking to the end is your benefactor. Few, but certain.',
    publicSelf: 'Unusual and deep thinker',
    trueSelf: 'Gave up early on being understood',
    cautions: ['Your mood swings make you unpredictable', 'Once absorbed, daily life collapses', 'The ordinary path does not work for you'],
    peak: {
      signals: ['A field others avoid calls for you', 'A long-held thought takes shape', 'You are handed an extreme situation'],
      story: 'This is when thoughts nobody else had get paid. A direction dismissed as odd suddenly matches the times. The strange road favors you over the ordinary one.',
      actions: ['Bring out the idea people called strange.', 'Take the seat that interprets and explains.', 'Leave your thinking in a form — writing, an object.'],
      miss: 'Your thinking deepens but never gets sent outside.',
    },
  },
  'uttara-bhadrapada': {
    ko: 'Uttara Bhadrapada',
    archetype: 'Serpent of Deep Waters',
    tagline: 'Has every reason to be angry and isn\'t — which is scarier',
    deityKo: 'Ahirbudhnya — serpent of the deep',
    symbolKo: 'Back legs of a funeral cot',
    yoniKo: 'Cow',
    rashi: ['Pisces'],
    luckyColor: 'Deep navy',
    gemstone: 'Blue sapphire',
    direction: 'West',
    keyword: 'Composure',
    copy: 'Almost nothing shakes you. Your voice does not rise even when it should, and you hear people out to the end. That steadiness is why people keep coming back.',
    ritual: 'When you feel rushed into a decision, always sleep on it.',
    strengths: ['Your feelings rise and fall without showing', 'You do not judge people carelessly', 'Long work does not bore you'],
    shadows: ['You hold back so much you no longer know what you want', 'Accepting change takes a long time', 'Past your limit, you quietly cut the relationship'],
    career: ['Counseling & welfare', 'Research & academia', 'Religion & practice', 'Long-term asset management'],
    love: {
      headline: 'Deep and quiet.',
      points: ['Being unshakable is your strength and the source of misunderstanding.', 'They may feel you do not react, so send a signal.', 'Once settled, you rarely waver.'],
    },
    wealth: {
      headline: 'Slow and safe money.',
      points: ['You miss most urgent opportunities, but you never lose big either.', 'Assets held long give you the best results.', 'The habit of sleeping on it when impatient protects your money.'],
    },
    work: {
      headline: 'The one who takes the long road.',
      points: ['Work where time is the value — counseling, scholarship, long-term management — suits you.', 'Not getting bored is your weapon.', 'Accepting change takes time.'],
    },
    bond: 'People lean on you because you barely waver. Of the 27, this is the most stable type in relationships.',
    helper: 'The people you listened to look after you on their own. They move without being asked.',
    publicSelf: 'Quiet and steady',
    trueSelf: 'Held back so long they no longer know what they want',
    cautions: ['You hold back and then quietly cut ties', 'Accepting change takes long', 'You miss most urgent chances'],
    peak: {
      signals: ['Results come from the seat you held for years', 'People start coming to you for counsel', 'Unhurried work becomes valuable'],
      story: 'This window deepens quietly. Rather than loud results, an unshakable seat is built. People come to you carrying their hardest problems.',
      actions: ['Take the role of mediating or sorting things out.', 'Lock in long-term assets and contracts in this window.', 'Say the thing you are holding back, at least once.'],
      miss: 'You neither get angry nor ask, so you keep absorbing the loss.',
    },
  },
  revati: {
    ko: 'Revati',
    archetype: 'The Guide Fish',
    tagline: 'Finds everyone else\'s way and delays their own',
    deityKo: 'Pushan — guardian of the road',
    symbolKo: 'Two fish',
    yoniKo: 'Elephant',
    rashi: ['Pisces'],
    luckyColor: 'Pale cream',
    gemstone: 'Emerald',
    direction: 'North',
    keyword: 'Guidance',
    copy: 'The last of the 27, and the seat that hands over to the next. Lost people keep finding you. You are good at finishing and seeing people off.',
    ritual: 'On the day you see someone off, walk them all the way to the door.',
    strengths: ['People feel safe beside you', 'Your endings are clean, with no loose ends', 'Kindness is genuinely your weapon'],
    shadows: ['Unable to refuse, work keeps coming in', 'You keep pushing your own turn back', 'You let money you are owed slide without a word'],
    career: ['Travel & logistics', 'Care & welfare', 'Education', 'Brokerage & agency'],
    love: {
      headline: 'Makes the other person comfortable.',
      points: ['Accommodating is second nature to you.', 'You have never actually said what you want.', 'Sometimes the other person never finds out.'],
    },
    wealth: {
      headline: 'Money that comes in while helping.',
      points: ['Opportunity comes from where you connected people.', 'Charging your full price on time is your biggest task.', 'Unable to refuse, you often let money you are owed go.'],
    },
    work: {
      headline: 'The one who hands over.',
      points: ['Value comes from brokerage, logistics, care, and education.', 'Your endings are clean, with no loose ends.', 'Unable to refuse, work keeps coming — that is the problem.'],
    },
    bond: 'You get along with anyone. But few know your true inside.',
    helper: 'Someone whose way you showed opens your way later. This type gets repaid for certain.',
    publicSelf: 'Kind and easy to be with',
    trueSelf: 'Has never said what they want',
    cautions: ['Unable to refuse, work keeps coming in', 'You keep pushing your turn back', 'You let money you are owed slide'],
    peak: {
      signals: ['Someone asks you to wrap things up', 'Opportunity comes from where you connected people', 'Care work becomes valuable'],
      story: 'This is the window for opening the way. Value comes from connecting people and finishing things, and long-dragging matters end. Before the next stage, everything gets tidied.',
      actions: ['Finish what needs finishing in this window.', 'Take the seat that connects people.', 'Decide your own reward first, then start.'],
      miss: 'Opening the way for others, you keep postponing your own schedule.',
    },
  },
}
